use pyo3::prelude::*;
use pyo3::types::PyDict;

mod owner_remap;

use owner_remap::set_meshlib_cut2origin_owner_remap;

pub(super) fn set_paired_cut_source_inventory(
    output: &Bound<'_, PyDict>,
    diagnostics: &zennah_geometry_core::ExactBooleanPipelineDiagnostics,
) -> PyResult<()> {
    macro_rules! set_diag {
        ($field:ident) => {
            output.set_item(stringify!($field), diagnostics.$field)?;
        };
        ($key:literal => $field:ident) => {
            output.set_item($key, diagnostics.$field)?;
        };
    }

    macro_rules! set_diag_clone {
        ($field:ident) => {
            output.set_item(stringify!($field), diagnostics.$field.clone())?;
        };
        ($key:literal => $field:ident) => {
            output.set_item($key, diagnostics.$field.clone())?;
        };
    }

    set_diag!(paired_coplanar_candidate_cut_faces);
    set_diag!(paired_coplanar_candidate_cut_source_records);
    set_diag!(paired_coplanar_candidate_cut_unique_source_faces);
    set_diag!(paired_coplanar_candidate_cut_duplicate_source_records);
    set_diag!(paired_coplanar_candidate_cut_fill_plans);
    set_diag!(paired_coplanar_candidate_cut_added_faces);
    set_diag!(paired_coplanar_candidate_replacement_cut_faces);
    set_diag!(paired_coplanar_candidate_replacement_cut_source_records);
    set_diag!(paired_coplanar_candidate_replacement_cut_unique_source_faces);
    set_diag!(paired_coplanar_candidate_replacement_cut_duplicate_source_records);
    set_diag!(paired_coplanar_candidate_replacement_cut_fill_plans);
    set_diag!(paired_coplanar_candidate_replacement_cut_added_faces);
    set_diag!(paired_coplanar_candidate_shadow_repaired_replacement_cut_faces);
    set_diag!(paired_coplanar_candidate_shadow_repaired_replacement_cut_source_records);
    set_diag!(paired_coplanar_candidate_shadow_repaired_replacement_cut_unique_source_faces);
    set_diag!(paired_coplanar_candidate_shadow_repaired_replacement_cut_duplicate_source_records);
    set_diag!(paired_coplanar_candidate_shadow_repaired_replacement_cut_fill_plans);
    set_diag!(paired_coplanar_candidate_shadow_repaired_replacement_cut_added_faces);
    set_diag!(paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_faces);
    set_diag!(
        paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_source_records
    );
    set_diag!(paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_unique_source_faces);
    set_diag!(paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_duplicate_source_records);
    set_diag!(paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_fill_plans);
    set_diag!(paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_added_faces);
    set_diag_clone!(paired_coplanar_candidate_first_shadow_repair_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_second_shadow_repair_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_first_shadow_repair_path_edges);
    set_diag_clone!(paired_coplanar_candidate_second_shadow_repair_path_edges);
    set_diag_clone!(paired_coplanar_candidate_first_shadow_repair_path_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_shadow_repair_path_source_faces);
    set_diag!(paired_coplanar_candidate_replacement_synthetic_contact_edges);
    set_diag!(paired_coplanar_candidate_replacement_barriered_first_prepare_part_dividable);
    set_diag!(paired_coplanar_candidate_replacement_barriered_second_prepare_part_dividable);
    set_diag_clone!(paired_coplanar_candidate_replacement_barriered_prepare_first_face_indices);
    set_diag_clone!(paired_coplanar_candidate_replacement_barriered_prepare_second_face_indices);
    set_diag!(paired_coplanar_candidate_replacement_barriered_first_cut_path_overlap_components);
    set_diag!(paired_coplanar_candidate_replacement_barriered_second_cut_path_overlap_components);
    set_diag_clone!(
        paired_coplanar_candidate_replacement_barriered_first_cut_path_overlap_component_indices
    );
    set_diag_clone!(
        paired_coplanar_candidate_replacement_barriered_second_cut_path_overlap_component_indices
    );
    set_diag_clone!(
        paired_coplanar_candidate_replacement_barriered_first_cut_path_overlap_component_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_replacement_barriered_second_cut_path_overlap_component_faces
    );
    set_diag!(paired_coplanar_candidate_replacement_fixed_barriered_first_prepare_part_dividable);
    set_diag!(paired_coplanar_candidate_replacement_fixed_barriered_second_prepare_part_dividable);
    set_diag_clone!(
        paired_coplanar_candidate_replacement_fixed_barriered_prepare_first_face_indices
    );
    set_diag_clone!(
        paired_coplanar_candidate_replacement_fixed_barriered_prepare_second_face_indices
    );
    set_diag!(
        paired_coplanar_candidate_replacement_fixed_barriered_first_cut_path_overlap_components
    );
    set_diag!(
        paired_coplanar_candidate_replacement_fixed_barriered_second_cut_path_overlap_components
    );
    set_diag_clone!(paired_coplanar_candidate_first_replacement_cut_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_second_replacement_cut_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_first_replacement_closed_cut_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_second_replacement_closed_cut_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_first_replacement_closed_cut_path_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_replacement_closed_cut_path_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_replacement_closed_cut_path_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_second_replacement_closed_cut_path_source_face_runs);
    set_diag_clone!(
        paired_coplanar_candidate_first_replacement_closed_cut_path_edge_adjacent_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_replacement_closed_cut_path_edge_adjacent_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_replacement_closed_cut_path_edge_left_primary_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_replacement_closed_cut_path_edge_left_primary_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_replacement_closed_cut_path_edge_right_primary_source_faces
    );
    set_diag_clone!(paired_coplanar_candidate_second_replacement_closed_cut_path_edge_right_primary_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_replacement_closed_cut_path_edge_left_primary_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_second_replacement_closed_cut_path_edge_left_primary_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_first_replacement_closed_cut_path_edge_right_primary_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_second_replacement_closed_cut_path_edge_right_primary_source_face_runs);
    set_diag_clone!(
        paired_coplanar_candidate_first_replacement_meshlib_removed_face_owner_candidates
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_replacement_meshlib_removed_face_owner_candidates
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_replacement_meshlib_removed_face_owner_candidate_runs
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_replacement_meshlib_removed_face_owner_candidate_runs
    );
    set_diag!(paired_coplanar_candidate_meshlib_cut2origin_shadow_source_records);
    set_diag!(paired_coplanar_candidate_meshlib_cut2origin_shadow_unique_source_faces);
    set_diag!(paired_coplanar_candidate_meshlib_cut2origin_shadow_duplicate_source_records);
    set_diag!(paired_coplanar_candidate_meshlib_cut2origin_shadow_split_source_records);
    set_diag!(paired_coplanar_candidate_meshlib_cut2origin_shadow_cut_event_source_records);
    set_diag!(paired_coplanar_candidate_meshlib_cut2origin_shadow_split_event_source_records);
    set_diag!(paired_coplanar_candidate_meshlib_cut2origin_shadow_prefill_repair_source_records);
    set_diag!(
        paired_coplanar_candidate_meshlib_cut2origin_shadow_open_edge_restoration_source_records
    );
    set_diag!(paired_coplanar_candidate_meshlib_cut2origin_shadow_orphan_repair_source_records);
    set_diag!(paired_coplanar_candidate_meshlib_cut2origin_shadow_fill_source_records);
    set_diag_clone!(paired_coplanar_candidate_first_cut_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_second_cut_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_first_closed_cut_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_second_closed_cut_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_first_cut_path_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_cut_path_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_cut_path_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_second_cut_path_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_first_closed_cut_path_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_closed_cut_path_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_closed_cut_path_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_second_closed_cut_path_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_first_cut_path_edge_adjacent_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_cut_path_edge_adjacent_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_closed_cut_path_edge_adjacent_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_closed_cut_path_edge_adjacent_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_cut_path_edge_left_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_cut_path_edge_left_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_cut_path_edge_right_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_cut_path_edge_right_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_closed_cut_path_edge_left_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_closed_cut_path_edge_left_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_closed_cut_path_edge_right_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_closed_cut_path_edge_right_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_closed_cut_path_edge_left_primary_source_faces);
    set_diag_clone!(
        paired_coplanar_candidate_second_closed_cut_path_edge_left_primary_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_closed_cut_path_edge_right_primary_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_closed_cut_path_edge_right_primary_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_closed_cut_path_edge_left_primary_source_face_runs
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_closed_cut_path_edge_left_primary_source_face_runs
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_closed_cut_path_edge_right_primary_source_face_runs
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_closed_cut_path_edge_right_primary_source_face_runs
    );
    set_diag_clone!(paired_coplanar_candidate_stitch_result_cut_path_lengths);
    set_diag_clone!(paired_coplanar_candidate_stitch_result_cut_edge_grouped_path_lengths);
    set_diag!(paired_coplanar_candidate_stitch_result_cut_edge_grouped_closed_paths);
    set_diag_clone!(paired_coplanar_candidate_first_stitch_result_cut_path_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_stitch_result_cut_path_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_stitch_result_cut_path_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_second_stitch_result_cut_path_source_face_runs);
    set_diag_clone!(
        paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_candidates
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_candidates
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_candidate_runs
    );
    set_diag_clone!(paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_candidate_runs);
    set_diag_clone!(
        paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_path_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_path_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_path_source_face_runs
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_path_source_face_runs
    );
    set_diag_clone!(paired_coplanar_candidate_first_stitch_result_cut_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_stitch_result_cut_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_stitch_result_cut_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_second_stitch_result_cut_source_face_runs);
    set_diag!(paired_coplanar_candidate_stitch_result_cut_missing_source_records);
    set_diag_clone!(
        paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_source_faces
    );
    set_diag_clone!(paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_source_face_runs);
    set_diag!(
        paired_coplanar_candidate_stitch_result_cut_meshlib_removed_face_owner_missing_records
    );
    set_diag_clone!(paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_source_faces);
    set_diag_clone!(
        paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_source_face_runs
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_source_face_runs
    );
    set_diag!(paired_coplanar_candidate_stitch_result_cut_edge_grouped_missing_source_records);
    set_diag_clone!(paired_coplanar_candidate_first_cut_source_face_counts);
    set_diag_clone!(paired_coplanar_candidate_second_cut_source_face_counts);
    set_diag_clone!(paired_coplanar_candidate_first_replacement_cut_source_face_counts);
    set_diag_clone!(paired_coplanar_candidate_second_replacement_cut_source_face_counts);
    set_diag_clone!(
        paired_coplanar_candidate_first_shadow_repaired_replacement_cut_source_face_counts
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_shadow_repaired_replacement_cut_source_face_counts
    );
    set_diag_clone!(paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_cut_source_face_counts);
    set_diag_clone!(paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_cut_source_face_counts);
    set_diag_clone!(paired_coplanar_candidate_first_replacement_fill_plan_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_replacement_fill_plan_source_faces);
    set_diag_clone!(paired_coplanar_candidate_first_replacement_fill_plan_added_faces);
    set_diag_clone!(paired_coplanar_candidate_second_replacement_fill_plan_added_faces);
    set_diag_clone!(
        paired_coplanar_candidate_first_shadow_repaired_replacement_fill_plan_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_shadow_repaired_replacement_fill_plan_source_faces
    );
    set_diag_clone!(paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_fill_plan_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_fill_plan_source_faces);
    set_diag_clone!(
        paired_coplanar_candidate_first_shadow_repaired_replacement_fill_plan_added_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_shadow_repaired_replacement_fill_plan_added_faces
    );
    set_diag_clone!(paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_fill_plan_added_faces);
    set_diag_clone!(paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_fill_plan_added_faces);
    set_diag_clone!(paired_coplanar_candidate_first_meshlib_cut2origin_shadow_source_face_counts);
    set_diag_clone!(paired_coplanar_candidate_second_meshlib_cut2origin_shadow_source_face_counts);
    set_diag_clone!(paired_coplanar_candidate_first_meshlib_cut2origin_shadow_vs_source_preserving_source_face_count_deltas);
    set_diag_clone!(paired_coplanar_candidate_second_meshlib_cut2origin_shadow_vs_source_preserving_source_face_count_deltas);
    set_diag_clone!(paired_coplanar_candidate_first_meshlib_cut2origin_shadow_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_second_meshlib_cut2origin_shadow_source_face_runs);
    set_diag_clone!(paired_coplanar_candidate_first_meshlib_cut2origin_shadow_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_meshlib_cut2origin_shadow_source_faces);
    set_diag_clone!(
        paired_coplanar_candidate_first_meshlib_cut2origin_shadow_appended_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_meshlib_cut2origin_shadow_appended_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_meshlib_cut2origin_shadow_appended_source_face_runs
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_meshlib_cut2origin_shadow_appended_source_face_runs
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_meshlib_cut2origin_shadow_prefill_repair_record_details
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_meshlib_cut2origin_shadow_prefill_repair_record_details
    );
    set_diag_clone!(paired_coplanar_candidate_first_meshlib_cut2origin_shadow_open_edge_restoration_record_details);
    set_diag_clone!(paired_coplanar_candidate_second_meshlib_cut2origin_shadow_open_edge_restoration_record_details);
    set_diag_clone!(
        paired_coplanar_candidate_first_meshlib_cut2origin_shadow_orphan_repair_record_details
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_meshlib_cut2origin_shadow_orphan_repair_record_details
    );
    set_diag_clone!(paired_coplanar_candidate_first_meshlib_cut2origin_shadow_split_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_meshlib_cut2origin_shadow_split_source_faces);
    set_diag_clone!(
        paired_coplanar_candidate_first_meshlib_cut2origin_shadow_cut_event_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_meshlib_cut2origin_shadow_cut_event_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_meshlib_cut2origin_shadow_split_event_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_meshlib_cut2origin_shadow_split_event_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_first_meshlib_cut2origin_shadow_prefill_repair_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_meshlib_cut2origin_shadow_prefill_repair_source_faces
    );
    set_diag_clone!(paired_coplanar_candidate_first_meshlib_cut2origin_shadow_open_edge_restoration_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_meshlib_cut2origin_shadow_open_edge_restoration_source_faces);
    set_diag_clone!(
        paired_coplanar_candidate_first_meshlib_cut2origin_shadow_orphan_repair_source_faces
    );
    set_diag_clone!(
        paired_coplanar_candidate_second_meshlib_cut2origin_shadow_orphan_repair_source_faces
    );
    set_diag_clone!(paired_coplanar_candidate_first_meshlib_cut2origin_shadow_fill_source_faces);
    set_diag_clone!(paired_coplanar_candidate_second_meshlib_cut2origin_shadow_fill_source_faces);
    set_meshlib_cut2origin_owner_remap(output, diagnostics)?;
    Ok(())
}
