'use client';

import type { ContextToolId, ReviewPane, RightDockTab, ToolbarGroup, WorkspaceCommandId } from './types';

export type CommandSurface = 'direct' | 'tool' | 'review' | 'activity';

export type WorkspaceCommandDefinition = {
  id: WorkspaceCommandId;
  group: ToolbarGroup;
  label: string;
  description: string;
  icon: string;
  surface: CommandSurface;
  dockTab?: RightDockTab;
  reviewPane?: ReviewPane;
  contextualToolId?: ContextToolId;
};

export const TOOLBAR_GROUP_ORDER: ToolbarGroup[] = ['file', 'prepare', 'modify', 'inspect', 'review'];

export const TOOLBAR_GROUP_LABELS: Record<ToolbarGroup, string> = {
  file: 'File',
  prepare: 'Prepare',
  modify: 'Modify',
  inspect: 'Inspect',
  review: 'Review',
};

export const WORKSPACE_COMMANDS: WorkspaceCommandDefinition[] = [
  {
    id: 'upload-new',
    group: 'file',
    label: 'Upload New',
    description: 'Start a new workspace from another model.',
    icon: 'UP',
    surface: 'direct',
  },
  {
    id: 'download-stl',
    group: 'file',
    label: 'Download STL',
    description: 'Export the current version manufacturing STL.',
    icon: 'ST',
    surface: 'direct',
  },
  {
    id: 'export-section',
    group: 'file',
    label: 'Export Section SVG',
    description: 'Export the current section contour as SVG.',
    icon: 'SV',
    surface: 'direct',
  },
  {
    id: 'repair',
    group: 'prepare',
    label: 'Auto Repair',
    description: 'Heal holes, degeneracies, and blockers before editing.',
    icon: 'AR',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'repair',
  },
  {
    id: 'fit-size',
    group: 'prepare',
    label: 'Fit To Size',
    description: 'Resize to a production ring size with axis-aware scaling.',
    icon: 'FS',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'fit-size',
  },
  {
    id: 'reduce-weight',
    group: 'prepare',
    label: 'Reduce Weight',
    description: 'Target a weight class while protecting detail-heavy regions.',
    icon: 'RW',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'reduce-weight',
  },
  {
    id: 'prepare-casting',
    group: 'prepare',
    label: 'Prepare For Casting',
    description: 'Build a castable hollow shell with conservative drain holes.',
    icon: 'PC',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'prepare-casting',
  },
  {
    id: 'make-manufacturable',
    group: 'prepare',
    label: 'Make Manufacturable',
    description: 'Run the guided repair, size, optimize, and validate flow.',
    icon: 'MM',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'make-manufacturable',
  },
  {
    id: 'resize',
    group: 'modify',
    label: 'Resize',
    description: 'Create a resized version with preserved ornament-heavy regions.',
    icon: 'RS',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'resize',
  },
  {
    id: 'protected-hollow',
    group: 'modify',
    label: 'Protected Hollow',
    description: 'Build a weighted shell while protecting decorative regions.',
    icon: 'PH',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'protected-hollow',
  },
  {
    id: 'offset-mesh',
    group: 'modify',
    label: 'Offset Mesh',
    description: 'Create an entire-model voxel offset child version.',
    icon: 'OF',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'offset-mesh',
  },
  {
    id: 'shell-mesh',
    group: 'modify',
    label: 'Shell Mesh',
    description: 'Create a voxel shell child version from the active mesh.',
    icon: 'SH',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'shell-mesh',
  },
  {
    id: 'thicken-mesh',
    group: 'modify',
    label: 'Thickening',
    description: 'Create a signed MeshLib thickenMesh child version.',
    icon: 'TH',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'thicken-mesh',
  },
  {
    id: 'weighted-shell',
    group: 'modify',
    label: 'Weighted Shell',
    description: 'Create a MeshLib weighted shell from selected region offsets.',
    icon: 'WS',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'weighted-shell',
  },
  {
    id: 'partial-offset',
    group: 'modify',
    label: 'Partial Offset',
    description: 'Offset selected regions and union the result with the source mesh.',
    icon: 'PO',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'partial-offset',
  },
  {
    id: 'offset-verts',
    group: 'modify',
    label: 'Offset Verts',
    description: 'Shift selected vertices along MeshLib pseudonormals.',
    icon: 'OV',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'offset-verts',
  },
  {
    id: 'expand-shrink',
    group: 'modify',
    label: 'Expand/Shrink',
    description: 'Smooth concave detail by offsetting outward and then inward.',
    icon: 'ES',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'expand-shrink',
  },
  {
    id: 'shrink-expand',
    group: 'modify',
    label: 'Shrink/Expand',
    description: 'Smooth convex detail by offsetting inward and then outward.',
    icon: 'SE',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'shrink-expand',
  },
  {
    id: 'hollow-drains',
    group: 'modify',
    label: 'Hollow + Drains',
    description: 'Build the protected shell and add drain holes.',
    icon: 'HD',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'hollow-drains',
  },
  {
    id: 'thicken-violations',
    group: 'modify',
    label: 'Thicken Violations',
    description: 'Only thicken unsafe areas below the minimum target.',
    icon: 'TV',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'thicken-violations',
  },
  {
    id: 'thicken-region',
    group: 'modify',
    label: 'Thicken Region',
    description: 'Apply a localized outward thickening pass to the primary region.',
    icon: 'TR',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'thicken-region',
  },
  {
    id: 'batch-thicken',
    group: 'modify',
    label: 'Batch Thicken',
    description: 'Thicken all batch-selected regions in one pass.',
    icon: 'BT',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'batch-thicken',
  },
  {
    id: 'scoop',
    group: 'modify',
    label: 'Scoop',
    description: 'Carve a controlled recess into a scoop-safe region.',
    icon: 'SC',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'scoop',
  },
  {
    id: 'smooth',
    group: 'modify',
    label: 'Smooth',
    description: 'Run a conservative localized or global smoothing pass.',
    icon: 'SM',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'smooth',
  },
  {
    id: 'batch-smooth',
    group: 'modify',
    label: 'Batch Smooth',
    description: 'Smooth all batch-selected regions with one command.',
    icon: 'BS',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'batch-smooth',
  },
  {
    id: 'decimate-mesh',
    group: 'modify',
    label: 'Decimate Mesh',
    description: 'Collapse shortest edges with the Rust MeshLib-style decimation subset.',
    icon: 'DC',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'decimate-mesh',
  },
  {
    id: 'subdivide-mesh',
    group: 'modify',
    label: 'Subdivide Mesh',
    description: 'Split long edges with MeshLib-style subdivision settings.',
    icon: 'SD',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'subdivide-mesh',
  },
  {
    id: 'make-delone',
    group: 'modify',
    label: 'Make Delone',
    description: 'Flip local diagonals with MeshLib-style Delone edge passes.',
    icon: 'DL',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'make-delone',
  },
  {
    id: 'section',
    group: 'inspect',
    label: 'Section',
    description: 'Inspect slice position, presets, contour stats, and export.',
    icon: 'SE',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'section',
  },
  {
    id: 'heatmap',
    group: 'inspect',
    label: 'Heatmap',
    description: 'Inspect wall thickness as a scalar overlay.',
    icon: 'HM',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'heatmap',
  },
  {
    id: 'regions',
    group: 'inspect',
    label: 'Regions',
    description: 'Inspect region coverage, selection, and allowed operations.',
    icon: 'RG',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'regions',
  },
  {
    id: 'measure-inspect',
    group: 'inspect',
    label: 'Measure / Inspect',
    description: 'Probe closest-surface distance, point pairs, and local thickness.',
    icon: 'MI',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'measure-inspect',
  },
  {
    id: 'mesh-cut-measure-path',
    group: 'inspect',
    label: 'Mesh Cut & Measure',
    description: 'Create a Rust-backed geodesic cut path and export it as ObjectLines.',
    icon: 'CM',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'mesh-cut-measure-path',
  },
  {
    id: 'offset-contours',
    group: 'inspect',
    label: 'Offset Contours',
    description: 'Apply MeshLib-style closed contour offsets through the Rust line kernel.',
    icon: 'OC',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'offset-contours',
  },
  {
    id: 'distance-map-from-mesh',
    group: 'inspect',
    label: 'Mesh Distance Map',
    description: 'Compute a MeshLib-style distance map from the active mesh through Rust.',
    icon: 'MD',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'distance-map-from-mesh',
  },
  {
    id: 'distance-map-contours',
    group: 'inspect',
    label: 'Contour Distance Map',
    description: 'Compute a MeshLib-style contour distance map through the Rust line kernel.',
    icon: 'DM',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'distance-map-contours',
  },
  {
    id: 'distance-map-iso-lines',
    group: 'inspect',
    label: 'Distance Map Iso-Lines',
    description: 'Extract MeshLib-style iso-line segments from a distance map through Rust.',
    icon: 'IL',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'distance-map-iso-lines',
  },
  {
    id: 'distance-map-merge',
    group: 'inspect',
    label: 'Distance Map Merge',
    description: 'Merge MeshLib-style distance maps with min, max, or subtract semantics through Rust.',
    icon: 'MM',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'distance-map-merge',
  },
  {
    id: 'distance-map-contour-boolean',
    group: 'inspect',
    label: 'Contour Boolean',
    description: 'Compose contour union, intersection, and subtraction through MeshLib-style signed distance maps.',
    icon: 'CB',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'distance-map-contour-boolean',
  },
  {
    id: 'distance-map-from-tiff',
    group: 'inspect',
    label: 'TIFF Distance Map Import',
    description: 'Load MeshLib-style TIFF distance maps through Rust.',
    icon: 'TI',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'distance-map-from-tiff',
  },
  {
    id: 'distance-map-to-tiff',
    group: 'inspect',
    label: 'TIFF Distance Map Export',
    description: 'Write MeshLib-style TIFF distance maps through Rust.',
    icon: 'TO',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'distance-map-to-tiff',
  },
  {
    id: 'object-lines-from-contours',
    group: 'inspect',
    label: 'ObjectLines From Contours',
    description: 'Build MeshLib ObjectLines scene JSON from contour polylines through Rust.',
    icon: 'OL',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'object-lines-from-contours',
  },
  {
    id: 'object-lines-load-mrlines',
    group: 'inspect',
    label: 'ObjectLines Load MrLines',
    description: 'Load MeshLib binary MrLines topology through Rust.',
    icon: 'LM',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'object-lines-load-mrlines',
  },
  {
    id: 'object-lines-save-mrlines',
    group: 'inspect',
    label: 'ObjectLines Save MrLines',
    description: 'Export MeshLib binary MrLines topology through Rust.',
    icon: 'SM',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'object-lines-save-mrlines',
  },
  {
    id: 'object-lines-load-ply',
    group: 'inspect',
    label: 'ObjectLines Load PLY',
    description: 'Load MeshLib PLY line vertex and edge payloads through Rust.',
    icon: 'LY',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'object-lines-load-ply',
  },
  {
    id: 'object-lines-save-ply',
    group: 'inspect',
    label: 'ObjectLines Save PLY',
    description: 'Export MeshLib binary little-endian PLY lines through Rust.',
    icon: 'SY',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'object-lines-save-ply',
  },
  {
    id: 'object-lines-load-pts',
    group: 'inspect',
    label: 'ObjectLines Load PTS',
    description: 'Load MeshLib PTS polyline blocks through Rust.',
    icon: 'LP',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'object-lines-load-pts',
  },
  {
    id: 'object-lines-save-pts',
    group: 'inspect',
    label: 'ObjectLines Save PTS',
    description: 'Export MeshLib PTS polyline blocks through Rust.',
    icon: 'SP',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'object-lines-save-pts',
  },
  {
    id: 'object-lines-load-svg',
    group: 'inspect',
    label: 'ObjectLines Load SVG',
    description: 'Load MeshLib SVG line geometry through Rust.',
    icon: 'LS',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'object-lines-load-svg',
  },
  {
    id: 'object-lines-save-dxf',
    group: 'inspect',
    label: 'ObjectLines Save DXF',
    description: 'Export MeshLib DXF polyline entities through Rust.',
    icon: 'DX',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'object-lines-save-dxf',
  },
  {
    id: 'object-lines-to-contours',
    group: 'inspect',
    label: 'ObjectLines To Contours',
    description: 'Restore contour polylines from MeshLib ObjectLines topology through Rust.',
    icon: 'LC',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'object-lines-to-contours',
  },
  {
    id: 'point-cloud-icp',
    group: 'inspect',
    label: 'Point Cloud / ICP',
    description: 'Align point-cloud samples through MeshLib-style Rust ICP registration.',
    icon: 'PC',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'point-cloud-icp',
  },
  {
    id: 'open-raw-voxels',
    group: 'inspect',
    label: 'Open RAW Voxels',
    description: 'Load MeshLib RAW voxel payloads through Rust.',
    icon: 'RV',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'open-raw-voxels',
  },
  {
    id: 'open-voxels-from-tiff',
    group: 'inspect',
    label: 'Open Voxels From TIFF',
    description: 'Load MeshLib TIFF voxel slice stacks through Rust.',
    icon: 'TV',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'open-voxels-from-tiff',
  },
  {
    id: 'gcode-parse-paths',
    group: 'inspect',
    label: 'G-code Path Parser',
    description: 'Parse CNC source into MeshLib-style toolpath segments.',
    icon: 'GC',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'gcode-parse-paths',
  },
  {
    id: 'gcode-load-source',
    group: 'inspect',
    label: 'Load G-code Source',
    description: 'Load a G-code source file through the Rust MeshLib-compatible parser.',
    icon: 'GL',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'gcode-parse-paths',
  },
  {
    id: 'gcode-write-source',
    group: 'inspect',
    label: 'Write G-code Source',
    description: 'Export G-code source frames through the Rust MeshLib-compatible writer.',
    icon: 'GW',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'gcode-parse-paths',
  },
  {
    id: 'gcode-parse-file-paths',
    group: 'inspect',
    label: 'Parse G-code File Paths',
    description: 'Load and parse G-code file paths with MeshLib-style linear movement semantics.',
    icon: 'GP',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'gcode-parse-paths',
  },
  {
    id: 'mesh-to-voxels-sdf',
    group: 'inspect',
    label: 'Mesh to Voxels / SDF',
    description: 'Convert the active mesh to a MeshLib-style signed or unsigned voxel distance field.',
    icon: 'VX',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'mesh-to-voxels-sdf',
  },
  {
    id: 'voxel-volume-render-ray',
    group: 'inspect',
    label: 'Volume Ray',
    description: 'Run Rust MeshLib-style volume ray compositing over a voxel grid.',
    icon: 'VR',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'voxel-volume-render-ray',
  },
  {
    id: 'exact-boolean',
    group: 'inspect',
    label: 'Exact Boolean',
    description: 'Run MeshLib-style exact boolean operations against another version.',
    icon: 'BO',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'exact-boolean',
  },
  {
    id: 'voxel-boolean',
    group: 'inspect',
    label: 'Voxel Boolean',
    description: 'Run MeshLib-style voxel boolean operations against another version.',
    icon: 'VB',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'voxel-boolean',
  },
  {
    id: 'collision-detect',
    group: 'inspect',
    label: 'Collision Detection',
    description: 'Find MeshLib-style colliding triangle pairs against another version.',
    icon: 'CD',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'collision-detect',
  },
  {
    id: 'wireframe',
    group: 'inspect',
    label: 'Wireframe',
    description: 'Toggle mesh wireframe for topology inspection.',
    icon: 'WF',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'wireframe',
  },
  {
    id: 'snapshots',
    group: 'inspect',
    label: 'Inspection Snapshots',
    description: 'Save and restore inspection states for repeated checks.',
    icon: 'IS',
    surface: 'tool',
    dockTab: 'tool',
    contextualToolId: 'snapshots',
  },
  {
    id: 'compare-versions',
    group: 'review',
    label: 'Compare Versions',
    description: 'Review cached compare overlays and switch compare targets.',
    icon: 'CV',
    surface: 'review',
    dockTab: 'review',
    reviewPane: 'compare',
  },
  {
    id: 'version-history',
    group: 'review',
    label: 'Version History',
    description: 'Open, compare, and branch historical versions.',
    icon: 'VH',
    surface: 'review',
    dockTab: 'review',
    reviewPane: 'history',
  },
  {
    id: 'restore-branch',
    group: 'review',
    label: 'Branch In History',
    description: 'Open version history and branch from a specific version.',
    icon: 'RB',
    surface: 'review',
    dockTab: 'review',
    reviewPane: 'history',
  },
  {
    id: 'job-activity',
    group: 'review',
    label: 'Job Activity',
    description: 'Monitor job progress and event history.',
    icon: 'JA',
    surface: 'activity',
    dockTab: 'activity',
  },
];

export const COMMANDS_BY_GROUP = TOOLBAR_GROUP_ORDER.reduce<Record<ToolbarGroup, WorkspaceCommandDefinition[]>>(
  (accumulator, group) => {
    accumulator[group] = WORKSPACE_COMMANDS.filter((command) => command.group === group);
    return accumulator;
  },
  {
    file: [],
    prepare: [],
    modify: [],
    inspect: [],
    review: [],
  },
);

export function isContextToolId(value: WorkspaceCommandId | null): value is ContextToolId {
  return !!value && WORKSPACE_COMMANDS.some((command) => command.contextualToolId === value);
}
