#!/usr/bin/env bash
# MeshInspector GCP deployment configuration.
#
#   cp deploy/config.example.sh deploy/config.sh   # config.sh is gitignored
#   # edit deploy/config.sh, then the scripts `source` it automatically.

# ----- GCP project / location -------------------------------------------------
export PROJECT_ID="CHANGE_ME"            # e.g. my-meshinspector-prod
export REGION="us-central1"              # Cloud Run + Cloud SQL + Artifact Registry

# ----- Artifact Registry ------------------------------------------------------
export AR_REPO="meshinspector"           # Docker repository name

# ----- Cloud SQL (PostgreSQL) -------------------------------------------------
export SQL_INSTANCE="meshinspector-db"
export SQL_TIER="db-custom-1-3840"       # 1 vCPU / 3.75 GB; scale as needed
export SQL_DB="meshinspector"
export SQL_USER="meshinspector"
# The DB password is generated by setup-gcp.sh and stored in Secret Manager.

# ----- Cloud Storage (object store, accessed via S3 interoperability) ---------
export GCS_BUCKET="${PROJECT_ID}-meshinspector-artifacts"   # must be globally unique
export OBJECT_STORE_PREFIX="artifacts"

# ----- Runtime service account ------------------------------------------------
export RUNTIME_SA="meshinspector-run"    # short name (setup-gcp.sh creates it)

# ----- Cloud Run service / job names ------------------------------------------
export API_SERVICE="meshinspector-api"
export WORKER_SERVICE="meshinspector-worker"
export FRONTEND_SERVICE="meshinspector-frontend"
export MIGRATE_JOB="meshinspector-migrate"

# ----- Secret Manager secret names (created by setup-gcp.sh) ------------------
export SECRET_DB_URL="meshinspector-database-url"
export SECRET_S3_KEY="meshinspector-s3-access-key"
export SECRET_S3_SECRET="meshinspector-s3-secret-key"

# ----- Service sizing ---------------------------------------------------------
export API_CPU="2";      export API_MEMORY="2Gi";   export API_MAX_INSTANCES="10"
export WORKER_CPU="2";   export WORKER_MEMORY="2Gi"
export FRONTEND_CPU="1"; export FRONTEND_MEMORY="512Mi"; export FRONTEND_MAX_INSTANCES="5"

# ----- Derived (do not edit) --------------------------------------------------
export AR_HOST="${REGION}-docker.pkg.dev"
export IMAGE_BASE="${AR_HOST}/${PROJECT_ID}/${AR_REPO}"
export SQL_CONN="${PROJECT_ID}:${REGION}:${SQL_INSTANCE}"
export RUNTIME_SA_EMAIL="${RUNTIME_SA}@${PROJECT_ID}.iam.gserviceaccount.com"
