mod aabb_tree;
mod analysis;
mod boolean;
mod compare_service;
mod convert;
mod deform;
mod deform_smooth;
mod deform_target;
mod distance;
mod features;
mod gcode;
mod health_service;
mod hollow;
mod hollow_shell;
mod jewelry;
mod lines;
mod manufacturability;
mod materials;
mod mesh;
mod mesh_edit;
mod mesh_quality;
mod point_cloud;
mod point_cloud_fill;
mod point_cloud_projection;
mod point_cloud_topology;
mod registration;
mod repair;
mod repair_components;
mod repair_degeneracy;
mod repair_diagnostics;
mod repair_holes;
mod repair_nonmanifold;
mod repair_smoothness;
mod repair_tunnels;
mod resize;
mod scalar_overlay;
mod sdf_grid;
mod sdf_marching;
mod signed_distance;
mod spatial;
mod spatial_intersections;
mod thickness;
mod topology;
mod voxel;
mod voxel_mesh_ops;
mod voxel_partial_offset;
use pyo3::prelude::*;
#[pymodule]
#[rustfmt::skip]
fn _zennah_geometry_rs(module: &Bound<'_, PyModule>) -> PyResult<()> {
    mesh::register(module)?; boolean::register(module)?; analysis::register(module)?; compare_service::register(module)?;
    scalar_overlay::register(module)?; spatial::register(module)?; spatial_intersections::register(module)?; thickness::register(module)?; aabb_tree::register(module)?;
    signed_distance::register(module)?; voxel::register(module)?; sdf_grid::register(module)?; sdf_marching::register(module)?; voxel_mesh_ops::register(module)?; voxel_partial_offset::register(module)?;
    deform::register(module)?; deform_smooth::register(module)?; deform_target::register(module)?; distance::register(module)?; features::register(module)?; gcode::register(module)?;
    health_service::register(module)?; resize::register(module)?; jewelry::register(module)?; lines::register(module)?; manufacturability::register(module)?;
    materials::register(module)?; mesh_edit::register(module)?; mesh_quality::register(module)?; hollow::register(module)?; hollow_shell::register(module)?;
    point_cloud::register(module)?; point_cloud_topology::register(module)?; point_cloud_fill::register(module)?; point_cloud_projection::register(module)?; registration::register(module)?;
    repair::register(module)?; repair_tunnels::register(module)?; repair_components::register(module)?; repair_diagnostics::register(module)?;
    repair_degeneracy::register(module)?; repair_nonmanifold::register(module)?; repair_holes::register(module)?; repair_smoothness::register(module)?; topology::register(module)?;
    Ok(())
}
