#[rustfmt::skip]
macro_rules! build_exact_boolean_pipeline_diagnostics {
    ($diagnostics_type:ident, $input:ident, $first_vertices_mixed_against_second:ident, $second_vertices_mixed_against_first:ident, $first_cut_edges:ident, $second_cut_edges:ident, $requires_topology_splice:ident, $possible_missing_cut_intersections:ident, $first_prepare_part_dividable:ident, $second_prepare_part_dividable:ident, $coplanar_overlap_pairs:ident, $coplanar_overlap_region_edges:ident, $coplanar_overlap_area:ident, $coplanar_overlap_contours:ident, $coplanar_overlap_contour_edges:ident, $paired_candidate:ident, $paired_candidate_active_volume_delta:ident, $paired_candidate_preserves_active_volume:ident, $stitch_cut_path_length_mismatches:ident, $output_mesh_stats:ident, $output_mesh_health:ident, $duplicate_output_face_groups:ident, $duplicate_output_faces:ident, $face_source_summary:ident, $raw_face_selection_summary:ident, $result_cut_summary:ident, $topology_splice_exported_mesh_stats:ident, $topology_splice_exported_mesh_health:ident, $topology_splice_export_changed_faces:ident, $meshlib:ident, $paired_coplanar_candidate_prepared_base_record_rewrite:ident, $paired_coplanar_candidate_meshlib_connect:ident, $paired_first_cut_inventory:ident, $paired_second_cut_inventory:ident, $paired_replacement_prepare:ident, $paired_first_replacement_cut_inventory:ident, $paired_second_replacement_cut_inventory:ident, $paired_first_shadow_repaired_replacement_cut_inventory:ident, $paired_second_shadow_repaired_replacement_cut_inventory:ident, $paired_first_replacement_cut_path_inventory:ident, $paired_second_replacement_cut_path_inventory:ident, $paired_first_cut2origin_shadow_inventory:ident, $paired_second_cut2origin_shadow_inventory:ident, $paired_first_source_preserving_meshlib_like_cut2origin_source_face_counts:ident, $paired_second_source_preserving_meshlib_like_cut2origin_source_face_counts:ident, $paired_first_meshlib_valid_cut_faces:ident, $paired_second_meshlib_valid_cut_faces:ident, $paired_first_cut2origin_shadow_owner_remap:ident, $paired_second_cut2origin_shadow_owner_remap:ident, $paired_owner_remapped_shadow_repaired_replacement_prepare:ident, $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_selected_lifecycle_coverage:ident, $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_selected_lifecycle_coverage:ident, $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_lifecycle_export_coverage:ident, $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_lifecycle_export_coverage:ident, $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_added_fill_lifecycle_export_coverage:ident, $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_added_fill_lifecycle_export_coverage:ident, $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_selected_lifecycle_slots:ident, $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_selected_lifecycle_slots:ident, $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_lifecycle_export_slots:ident, $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_lifecycle_export_slots:ident, $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_added_fill_lifecycle_export_slots:ident, $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_added_fill_lifecycle_export_slots:ident, $paired_first_owner_remapped_shadow_repaired_replacement_cut_inventory:ident, $paired_second_owner_remapped_shadow_repaired_replacement_cut_inventory:ident, $paired_first_cut2origin_shadow_vs_source_preserving_source_face_count_deltas:ident, $paired_second_cut2origin_shadow_vs_source_preserving_source_face_count_deltas:ident, $paired_first_cut_path_inventory:ident, $paired_second_cut_path_inventory:ident, $paired_stitch_result_cut_source_inventory:ident, $parity_ready:ident) => {
        Ok($diagnostics_type {
            first_cut_edges: $first_cut_edges,
            second_cut_edges: $second_cut_edges,
            first_skipped_source_faces: $input.first_cut.mesh.skipped_source_faces.clone(),
            second_skipped_source_faces: $input.second_cut.mesh.skipped_source_faces.clone(),
            first_fill_plans: $input.first_cut.fill_plans.len(),
            second_fill_plans: $input.second_cut.fill_plans.len(),
            stitch_compatible: $input.stitch_plan.compatible,
            stitch_unmatched_first_edges: $input.stitch_plan.unmatched_first_edges.len(),
            stitch_unmatched_second_edges: $input.stitch_plan.unmatched_second_edges.len(),
            stitch_cut_path_length_mismatches: $stitch_cut_path_length_mismatches,
            requires_topology_splice: $requires_topology_splice,
            first_vertices_mixed_against_second: $first_vertices_mixed_against_second,
            second_vertices_mixed_against_first: $second_vertices_mixed_against_first,
            possible_missing_cut_intersections: $possible_missing_cut_intersections,
            first_prepare_part_dividable: $first_prepare_part_dividable,
            second_prepare_part_dividable: $second_prepare_part_dividable,
            first_cut_path_side_components: $input.assembly.first_cut_path_side_components,
            second_cut_path_side_components: $input.assembly.second_cut_path_side_components,
            first_cut_path_overlap_components: $input.assembly.first_cut_path_overlap_components,
            second_cut_path_overlap_components: $input.assembly.second_cut_path_overlap_components,
            coplanar_overlap_pairs: $coplanar_overlap_pairs,
            coplanar_overlap_region_edges: $coplanar_overlap_region_edges,
            coplanar_overlap_area: $coplanar_overlap_area,
            coplanar_overlap_contours: $coplanar_overlap_contours,
            coplanar_overlap_contour_edges: $coplanar_overlap_contour_edges,
            coplanar_cut_trial_contours: super::topology::trial_usize($input.coplanar_cut_trial, |trial| trial.contours),
            coplanar_cut_trial_contour_edges: super::topology::trial_usize($input.coplanar_cut_trial, |trial| { trial.contour_edges }),
            coplanar_cut_trial_first_cut_edges: super::topology::trial_usize($input.coplanar_cut_trial, |trial| { trial.first_cut_edges }),
            coplanar_cut_trial_second_cut_edges: super::topology::trial_usize($input.coplanar_cut_trial, |trial| { trial.second_cut_edges }),
            paired_coplanar_cut_trial_contours: super::topology::trial_usize($input.coplanar_cut_trial, |trial| { trial.paired_contours }),
            paired_coplanar_cut_trial_contour_edges: super::topology::trial_usize($input.coplanar_cut_trial, |trial| { trial.paired_contour_edges }),
            paired_coplanar_cut_trial_first_cut_edges: super::topology::trial_usize($input.coplanar_cut_trial, |trial| { trial.paired_first_cut_edges }),
            paired_coplanar_cut_trial_second_cut_edges: super::topology::trial_usize( $input.coplanar_cut_trial, |trial| trial.paired_second_cut_edges, ),
            paired_coplanar_combined_first_cut_path_lengths: $input .coplanar_cut_trial .map(|trial| trial.paired_combined_first_cut_path_lengths.clone()) .unwrap_or_default(),
            paired_coplanar_combined_second_cut_path_lengths: $input .coplanar_cut_trial .map(|trial| trial.paired_combined_second_cut_path_lengths.clone()) .unwrap_or_default(),
            paired_coplanar_combined_first_cut_path_source_faces: $input .coplanar_cut_trial .map(|trial| trial.paired_combined_first_cut_path_source_faces.clone()) .unwrap_or_default(),
            paired_coplanar_combined_second_cut_path_source_faces: $input .coplanar_cut_trial .map(|trial| trial.paired_combined_second_cut_path_source_faces.clone()) .unwrap_or_default(),
            paired_coplanar_combined_first_cut_path_source_face_runs: $input .coplanar_cut_trial .map(|trial| trial.paired_combined_first_cut_path_source_face_runs.clone()) .unwrap_or_default(),
            paired_coplanar_combined_second_cut_path_source_face_runs: $input .coplanar_cut_trial .map(|trial| trial.paired_combined_second_cut_path_source_face_runs.clone()) .unwrap_or_default(),
            paired_coplanar_combined_first_collapsed_cut_path_lengths: $input .coplanar_cut_trial .map(|trial| trial.paired_combined_first_collapsed_cut_path_lengths.clone()) .unwrap_or_default(),
            paired_coplanar_combined_second_collapsed_cut_path_lengths: $input .coplanar_cut_trial .map(|trial| trial.paired_combined_second_collapsed_cut_path_lengths.clone()) .unwrap_or_default(),
            paired_coplanar_combined_first_collapsed_cut_path_source_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_collapsed_cut_path_source_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_collapsed_cut_path_source_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_collapsed_cut_path_source_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_collapsed_cut_path_source_face_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_collapsed_cut_path_source_face_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_collapsed_cut_path_source_face_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_collapsed_cut_path_source_face_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_cut_path_lengths: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_cut_path_lengths .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_cut_path_lengths: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_cut_path_lengths .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_cut_path_source_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_cut_path_source_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_cut_path_source_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_cut_path_source_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_cut_path_source_face_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_cut_path_source_face_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_cut_path_source_face_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_cut_path_source_face_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_cut_path_collapsed: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_cut_path_collapsed .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_cut_path_collapsed: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_cut_path_collapsed .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_cut_path_start_primitive_kinds: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_cut_path_start_primitive_kinds .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_cut_path_start_primitive_kinds: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_cut_path_start_primitive_kinds .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_cut_path_start_primitive_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_cut_path_start_primitive_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_cut_path_start_primitive_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_cut_path_start_primitive_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_order_rotations: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_order_rotations .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_order_rotations: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_order_rotations .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_cut_path_start_primitive_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_cut_path_start_primitive_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_cut_path_start_primitive_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_cut_path_start_primitive_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_cut_path_collapsed: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_cut_path_collapsed .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_cut_path_collapsed: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_cut_path_collapsed .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_cut_edge_paths: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_cut_edge_paths .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_cut_edge_paths: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_cut_edge_paths .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_removed_face_owner_candidates: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_removed_face_owner_candidates .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_removed_face_owner_candidates: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_removed_face_owner_candidates .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_collapsed_removed_face_owner_candidates: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_collapsed_removed_face_owner_candidates .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_collapsed_removed_face_owner_candidates: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_collapsed_removed_face_owner_candidates .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_collapsed_removed_face_owner_candidate_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_collapsed_removed_face_owner_candidate_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_collapsed_removed_face_owner_candidate_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_collapsed_removed_face_owner_candidate_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_removed_face_owner_candidate_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_removed_face_owner_candidate_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_removed_face_owner_candidate_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_removed_face_owner_candidate_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_replacement_source_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_replacement_source_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_replacement_source_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_replacement_source_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_replacement_source_face_counts: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_replacement_source_face_counts .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_replacement_source_face_counts: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_replacement_source_face_counts .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_replacement_source_face_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_replacement_source_face_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_replacement_source_face_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_replacement_source_face_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_replacement_lifecycle_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_replacement_lifecycle_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_replacement_lifecycle_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_replacement_lifecycle_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_replacement_lifecycle_slot_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_replacement_lifecycle_slot_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_replacement_lifecycle_slot_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_replacement_lifecycle_slot_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_cut2origin_source_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_cut2origin_source_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_cut2origin_source_faces: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_cut2origin_source_faces .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_like_cut2origin_source_face_counts: $paired_first_source_preserving_meshlib_like_cut2origin_source_face_counts,
            paired_coplanar_combined_second_source_preserving_meshlib_like_cut2origin_source_face_counts: $paired_second_source_preserving_meshlib_like_cut2origin_source_face_counts,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_vs_source_preserving_source_face_count_deltas: $paired_first_cut2origin_shadow_vs_source_preserving_source_face_count_deltas,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_vs_source_preserving_source_face_count_deltas: $paired_second_cut2origin_shadow_vs_source_preserving_source_face_count_deltas,
            paired_coplanar_combined_first_source_preserving_meshlib_like_cut2origin_source_face_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_like_cut2origin_source_face_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_like_cut2origin_source_face_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_like_cut2origin_source_face_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_removed_face_owner_candidates: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_removed_face_owner_candidates .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_removed_face_owner_candidates: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_removed_face_owner_candidates .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_first_source_preserving_meshlib_removed_face_owner_candidate_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_first_source_preserving_meshlib_removed_face_owner_candidate_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_second_source_preserving_meshlib_removed_face_owner_candidate_runs: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_second_source_preserving_meshlib_removed_face_owner_candidate_runs .clone() }) .unwrap_or_default(),
            paired_coplanar_combined_source_preserving_meshlib_removed_face_owner_missing_records: $input .coplanar_cut_trial .map(|trial| { trial .paired_combined_source_preserving_meshlib_removed_face_owner_missing_records }) .unwrap_or_default(),
            paired_coplanar_combined_duplicate_first_path_edge_occurrences: super::topology::trial_usize( $input.coplanar_cut_trial, |trial| trial.paired_combined_duplicate_first_path_edge_occurrences, ),
            paired_coplanar_combined_duplicate_second_path_edge_occurrences: super::topology::trial_usize( $input.coplanar_cut_trial, |trial| trial.paired_combined_duplicate_second_path_edge_occurrences, ),
            paired_coplanar_combined_duplicate_first_path_edge_path_indices: super::topology::trial_vec_vec_usize( $input.coplanar_cut_trial, |trial| &trial.paired_combined_duplicate_first_path_edge_path_indices, ),
            paired_coplanar_combined_duplicate_second_path_edge_path_indices: super::topology::trial_vec_vec_usize( $input.coplanar_cut_trial, |trial| &trial.paired_combined_duplicate_second_path_edge_path_indices, ),
            paired_coplanar_stitch_cut_path_length_mismatches: super::topology::trial_usize( $input.coplanar_cut_trial, |trial| trial.paired_stitch_cut_path_length_mismatches, ),
            paired_coplanar_stitch_unmatched_first_edges: super::topology::trial_usize( $input.coplanar_cut_trial, |trial| trial.paired_stitch_unmatched_first_edges, ),
            paired_coplanar_stitch_unmatched_second_edges: super::topology::trial_usize( $input.coplanar_cut_trial, |trial| trial.paired_stitch_unmatched_second_edges, ),
            paired_coplanar_duplicate_first_path_edges: super::topology::trial_usize( $input.coplanar_cut_trial, |trial| trial.paired_duplicate_first_path_edges, ),
            paired_coplanar_duplicate_second_path_edges: super::topology::trial_usize( $input.coplanar_cut_trial, |trial| trial.paired_duplicate_second_path_edges, ),
            paired_coplanar_duplicate_first_path_edge_occurrences: super::topology::trial_usize( $input.coplanar_cut_trial, |trial| trial.paired_duplicate_first_path_edge_occurrences, ),
            paired_coplanar_duplicate_second_path_edge_occurrences: super::topology::trial_usize( $input.coplanar_cut_trial, |trial| trial.paired_duplicate_second_path_edge_occurrences, ),
            paired_coplanar_duplicate_first_path_edge_path_indices: super::topology::trial_vec_vec_usize( $input.coplanar_cut_trial, |trial| &trial.paired_duplicate_first_path_edge_path_indices, ),
            paired_coplanar_duplicate_second_path_edge_path_indices: super::topology::trial_vec_vec_usize( $input.coplanar_cut_trial, |trial| &trial.paired_duplicate_second_path_edge_path_indices, ),
            paired_coplanar_candidate_stitch_compatible: $paired_candidate.stitch_compatible,
            paired_coplanar_candidate_first_prepare_part_dividable: $paired_candidate .$first_prepare_part_dividable,
            paired_coplanar_candidate_second_prepare_part_dividable: $paired_candidate .$second_prepare_part_dividable,
            paired_coplanar_candidate_prepare_first_face_indices: $paired_candidate .prepare_first_face_indices,
            paired_coplanar_candidate_prepare_second_face_indices: $paired_candidate .prepare_second_face_indices,
            paired_coplanar_candidate_selected_first_face_indices: $paired_candidate .selected_first_face_indices,
            paired_coplanar_candidate_selected_second_face_indices: $paired_candidate .selected_second_face_indices,
            paired_coplanar_candidate_replacement_first_prepare_part_dividable: $paired_replacement_prepare.$first_prepare_part_dividable,
            paired_coplanar_candidate_replacement_second_prepare_part_dividable: $paired_replacement_prepare.$second_prepare_part_dividable,
            paired_coplanar_candidate_replacement_prepare_first_face_indices: $paired_replacement_prepare.prepare_first_face_indices,
            paired_coplanar_candidate_replacement_prepare_second_face_indices: $paired_replacement_prepare.prepare_second_face_indices,
            paired_coplanar_candidate_replacement_selected_first_face_indices: $paired_replacement_prepare.selected_first_face_indices,
            paired_coplanar_candidate_replacement_selected_second_face_indices: $paired_replacement_prepare.selected_second_face_indices,
            paired_coplanar_candidate_replacement_first_cut_path_side_components: $paired_replacement_prepare.first_cut_path_side_components,
            paired_coplanar_candidate_replacement_second_cut_path_side_components: $paired_replacement_prepare.second_cut_path_side_components,
            paired_coplanar_candidate_replacement_first_cut_path_overlap_components: $paired_replacement_prepare.first_cut_path_overlap_components,
            paired_coplanar_candidate_replacement_second_cut_path_overlap_components: $paired_replacement_prepare.second_cut_path_overlap_components,
            paired_coplanar_candidate_replacement_first_cut_path_component_faces: $paired_replacement_prepare.first_cut_path_component_faces,
            paired_coplanar_candidate_replacement_second_cut_path_component_faces: $paired_replacement_prepare.second_cut_path_component_faces,
            paired_coplanar_candidate_replacement_first_cut_path_left_component_indices: $paired_replacement_prepare.first_cut_path_left_component_indices,
            paired_coplanar_candidate_replacement_second_cut_path_left_component_indices: $paired_replacement_prepare.second_cut_path_left_component_indices,
            paired_coplanar_candidate_replacement_first_cut_path_right_component_indices: $paired_replacement_prepare.first_cut_path_right_component_indices,
            paired_coplanar_candidate_replacement_second_cut_path_right_component_indices: $paired_replacement_prepare.second_cut_path_right_component_indices,
            paired_coplanar_candidate_replacement_first_cut_path_overlap_component_indices: $paired_replacement_prepare.first_cut_path_overlap_component_indices,
            paired_coplanar_candidate_replacement_second_cut_path_overlap_component_indices: $paired_replacement_prepare.second_cut_path_overlap_component_indices,
            paired_coplanar_candidate_replacement_first_cut_path_left_component_faces: $paired_replacement_prepare.first_cut_path_left_component_faces,
            paired_coplanar_candidate_replacement_second_cut_path_left_component_faces: $paired_replacement_prepare.second_cut_path_left_component_faces,
            paired_coplanar_candidate_replacement_first_cut_path_right_component_faces: $paired_replacement_prepare.first_cut_path_right_component_faces,
            paired_coplanar_candidate_replacement_second_cut_path_right_component_faces: $paired_replacement_prepare.second_cut_path_right_component_faces,
            paired_coplanar_candidate_replacement_first_cut_path_overlap_component_faces: $paired_replacement_prepare.first_cut_path_overlap_component_faces,
            paired_coplanar_candidate_replacement_second_cut_path_overlap_component_faces: $paired_replacement_prepare.second_cut_path_overlap_component_faces,
            paired_coplanar_candidate_replacement_result_cut_paths_complete: $paired_replacement_prepare.result_cut_paths_complete,
            paired_coplanar_candidate_replacement_prepare_cut_complete: $paired_replacement_prepare.prepare_result_cut_paths_complete,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_first_prepare_part_dividable: $paired_owner_remapped_shadow_repaired_replacement_prepare.$first_prepare_part_dividable,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_second_prepare_part_dividable: $paired_owner_remapped_shadow_repaired_replacement_prepare.$second_prepare_part_dividable,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_result_cut_paths_complete: $paired_owner_remapped_shadow_repaired_replacement_prepare.result_cut_paths_complete,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_prepare_cut_complete: $paired_owner_remapped_shadow_repaired_replacement_prepare .prepare_result_cut_paths_complete,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_prepare_first_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .prepare_first_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_prepare_second_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .prepare_second_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_selected_first_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .selected_first_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_selected_second_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .selected_second_face_indices,
            paired_coplanar_candidate_first_cut_path_side_components: $paired_candidate .first_cut_path_side_components,
            paired_coplanar_candidate_second_cut_path_side_components: $paired_candidate .second_cut_path_side_components,
            paired_coplanar_candidate_first_cut_path_overlap_components: $paired_candidate .first_cut_path_overlap_components,
            paired_coplanar_candidate_second_cut_path_overlap_components: $paired_candidate .second_cut_path_overlap_components,
            paired_coplanar_candidate_result_cut_paths_complete: $paired_candidate .result_cut_paths_complete,
            paired_coplanar_candidate_prepare_cut_complete: $paired_candidate .prepare_result_cut_paths_complete,
            paired_coplanar_candidate_output_faces: $paired_candidate.output_faces,
            paired_coplanar_candidate_output_area: $paired_candidate.output_area,
            paired_coplanar_candidate_output_volume: $paired_candidate.output_volume,
            paired_coplanar_candidate_self_intersections: $paired_candidate.output_self_intersections,
            paired_coplanar_candidate_self_intersections_available: $paired_candidate .output_self_intersections_available,
            paired_coplanar_candidate_active_volume_delta: $paired_candidate_active_volume_delta,
            paired_coplanar_candidate_preserves_active_volume: $paired_candidate_preserves_active_volume,
            paired_coplanar_candidate_boundary_edges: $paired_candidate.boundary_edges,
            paired_coplanar_candidate_nonmanifold_edges: $paired_candidate.nonmanifold_edges,
            paired_coplanar_candidate_duplicate_output_faces: $paired_candidate.$duplicate_output_faces,
            paired_coplanar_candidate_meshlib_base_faces: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.base_faces),
            paired_coplanar_candidate_meshlib_incoming_faces: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.incoming_faces),
            paired_coplanar_candidate_meshlib_base_vertices: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.base_vertices),
            paired_coplanar_candidate_meshlib_incoming_vertices: $paired_coplanar_candidate_meshlib_connect.map_or(0, |summary| summary.incoming_vertices),
            paired_coplanar_candidate_meshlib_unstitched_faces: $paired_coplanar_candidate_meshlib_connect.map_or(0, |summary| summary.unstitched_faces),
            paired_coplanar_candidate_meshlib_unstitched_vertices: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.unstitched_vertices),
            paired_coplanar_candidate_meshlib_path_pairs: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.path_pairs),
            paired_coplanar_candidate_meshlib_path_count_mismatch: $paired_coplanar_candidate_meshlib_connect .is_some_and(|summary| summary.path_count_mismatch),
            paired_coplanar_candidate_meshlib_path_length_mismatches: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.path_length_mismatches),
            paired_coplanar_candidate_meshlib_path_closed_mismatches: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.path_closed_mismatches),
            paired_coplanar_candidate_meshlib_path_coordinate_mismatches: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.path_coordinate_mismatches),
            paired_coplanar_candidate_meshlib_path_same_direction_edges: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.path_same_direction_edges),
            paired_coplanar_candidate_meshlib_path_reversed_edges: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.path_reversed_edges),
            paired_coplanar_candidate_meshlib_base_mapped_cut_path_edges: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.base_mapped_cut_path_edges),
            paired_coplanar_candidate_meshlib_incoming_mapped_cut_path_edges: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.incoming_mapped_cut_path_edges),
            paired_coplanar_candidate_meshlib_base_missing_cut_path_edges: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.base_missing_cut_path_edges),
            paired_coplanar_candidate_meshlib_incoming_missing_cut_path_edges: $paired_coplanar_candidate_meshlib_connect .map_or(0, |summary| summary.incoming_missing_cut_path_edges),
            paired_coplanar_candidate_meshlib_base_cut_paths_complete: $paired_coplanar_candidate_meshlib_connect .is_some_and(|summary| summary.base_cut_paths_complete),
            paired_coplanar_candidate_meshlib_incoming_cut_paths_complete: $paired_coplanar_candidate_meshlib_connect .is_some_and(|summary| summary.incoming_cut_paths_complete),
            paired_coplanar_candidate_cut_faces: [ $paired_first_cut_inventory.faces, $paired_second_cut_inventory.faces, ],
            paired_coplanar_candidate_cut_source_records: [ $paired_first_cut_inventory.source_records, $paired_second_cut_inventory.source_records, ],
            paired_coplanar_candidate_cut_unique_source_faces: [ $paired_first_cut_inventory.unique_source_faces, $paired_second_cut_inventory.unique_source_faces, ],
            paired_coplanar_candidate_cut_duplicate_source_records: [ $paired_first_cut_inventory.duplicate_source_records, $paired_second_cut_inventory.duplicate_source_records, ],
            paired_coplanar_candidate_cut_fill_plans: [ $paired_first_cut_inventory.fill_plans, $paired_second_cut_inventory.fill_plans, ],
            paired_coplanar_candidate_cut_added_faces: [ $paired_first_cut_inventory.added_faces, $paired_second_cut_inventory.added_faces, ],
            paired_coplanar_candidate_replacement_cut_faces: [ $paired_first_replacement_cut_inventory.faces, $paired_second_replacement_cut_inventory.faces, ],
            paired_coplanar_candidate_replacement_cut_source_records: [ $paired_first_replacement_cut_inventory.source_records, $paired_second_replacement_cut_inventory.source_records, ],
            paired_coplanar_candidate_replacement_cut_unique_source_faces: [ $paired_first_replacement_cut_inventory.unique_source_faces, $paired_second_replacement_cut_inventory.unique_source_faces, ],
            paired_coplanar_candidate_replacement_cut_duplicate_source_records: [ $paired_first_replacement_cut_inventory.duplicate_source_records, $paired_second_replacement_cut_inventory.duplicate_source_records, ],
            paired_coplanar_candidate_replacement_cut_fill_plans: [ $paired_first_replacement_cut_inventory.fill_plans, $paired_second_replacement_cut_inventory.fill_plans, ],
            paired_coplanar_candidate_replacement_cut_added_faces: [ $paired_first_replacement_cut_inventory.added_faces, $paired_second_replacement_cut_inventory.added_faces, ],
            paired_coplanar_candidate_shadow_repaired_replacement_cut_faces: [ $paired_first_shadow_repaired_replacement_cut_inventory.faces, $paired_second_shadow_repaired_replacement_cut_inventory.faces, ],
            paired_coplanar_candidate_shadow_repaired_replacement_cut_source_records: [ $paired_first_shadow_repaired_replacement_cut_inventory.source_records, $paired_second_shadow_repaired_replacement_cut_inventory.source_records, ],
            paired_coplanar_candidate_shadow_repaired_replacement_cut_unique_source_faces: [ $paired_first_shadow_repaired_replacement_cut_inventory.unique_source_faces, $paired_second_shadow_repaired_replacement_cut_inventory.unique_source_faces, ],
            paired_coplanar_candidate_shadow_repaired_replacement_cut_duplicate_source_records: [ $paired_first_shadow_repaired_replacement_cut_inventory.duplicate_source_records, $paired_second_shadow_repaired_replacement_cut_inventory.duplicate_source_records, ],
            paired_coplanar_candidate_shadow_repaired_replacement_cut_fill_plans: [ $paired_first_shadow_repaired_replacement_cut_inventory.fill_plans, $paired_second_shadow_repaired_replacement_cut_inventory.fill_plans, ],
            paired_coplanar_candidate_shadow_repaired_replacement_cut_added_faces: [ $paired_first_shadow_repaired_replacement_cut_inventory.added_faces, $paired_second_shadow_repaired_replacement_cut_inventory.added_faces, ],
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_faces: [ $paired_first_owner_remapped_shadow_repaired_replacement_cut_inventory.faces, $paired_second_owner_remapped_shadow_repaired_replacement_cut_inventory.faces, ],
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_source_records: [ $paired_first_owner_remapped_shadow_repaired_replacement_cut_inventory.source_records, $paired_second_owner_remapped_shadow_repaired_replacement_cut_inventory.source_records, ],
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_unique_source_faces: [ $paired_first_owner_remapped_shadow_repaired_replacement_cut_inventory .unique_source_faces, $paired_second_owner_remapped_shadow_repaired_replacement_cut_inventory .unique_source_faces, ],
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_duplicate_source_records: [ $paired_first_owner_remapped_shadow_repaired_replacement_cut_inventory .duplicate_source_records, $paired_second_owner_remapped_shadow_repaired_replacement_cut_inventory .duplicate_source_records, ],
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_fill_plans: [ $paired_first_owner_remapped_shadow_repaired_replacement_cut_inventory.fill_plans, $paired_second_owner_remapped_shadow_repaired_replacement_cut_inventory.fill_plans, ],
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_added_faces: [ $paired_first_owner_remapped_shadow_repaired_replacement_cut_inventory.added_faces, $paired_second_owner_remapped_shadow_repaired_replacement_cut_inventory.added_faces, ],
            paired_coplanar_candidate_first_shadow_repair_path_lengths: $input .paired_coplanar_candidate_parts .map(|parts| { parts .first_shadow_repair_paths .iter() .map(|repair| repair.path.len()) .collect() }) .unwrap_or_default(),
            paired_coplanar_candidate_second_shadow_repair_path_lengths: $input .paired_coplanar_candidate_parts .map(|parts| { parts .second_shadow_repair_paths .iter() .map(|repair| repair.path.len()) .collect() }) .unwrap_or_default(),
            paired_coplanar_candidate_first_shadow_repair_path_edges: $input .paired_coplanar_candidate_parts .map(|parts| { parts .first_shadow_repair_paths .iter() .map(|repair| repair.path.clone()) .collect() }) .unwrap_or_default(),
            paired_coplanar_candidate_second_shadow_repair_path_edges: $input .paired_coplanar_candidate_parts .map(|parts| { parts .second_shadow_repair_paths .iter() .map(|repair| repair.path.clone()) .collect() }) .unwrap_or_default(),
            paired_coplanar_candidate_first_shadow_repair_path_source_faces: $input .paired_coplanar_candidate_parts .map(|parts| shadow_repair_path_source_faces(&parts.first_shadow_repair_paths)) .unwrap_or_default(),
            paired_coplanar_candidate_second_shadow_repair_path_source_faces: $input .paired_coplanar_candidate_parts .map(|parts| shadow_repair_path_source_faces(&parts.second_shadow_repair_paths)) .unwrap_or_default(),
            paired_coplanar_candidate_replacement_synthetic_contact_edges: $paired_replacement_prepare.synthetic_contact_edges,
            paired_coplanar_candidate_replacement_barriered_first_prepare_part_dividable: $paired_replacement_prepare.barriered_first_prepare_part_dividable,
            paired_coplanar_candidate_replacement_barriered_second_prepare_part_dividable: $paired_replacement_prepare.barriered_second_prepare_part_dividable,
            paired_coplanar_candidate_replacement_barriered_prepare_first_face_indices: $paired_replacement_prepare.barriered_prepare_first_face_indices,
            paired_coplanar_candidate_replacement_barriered_prepare_second_face_indices: $paired_replacement_prepare.barriered_prepare_second_face_indices,
            paired_coplanar_candidate_replacement_barriered_first_cut_path_overlap_components: $paired_replacement_prepare.barriered_first_cut_path_overlap_components,
            paired_coplanar_candidate_replacement_barriered_second_cut_path_overlap_components: $paired_replacement_prepare.barriered_second_cut_path_overlap_components,
            paired_coplanar_candidate_replacement_barriered_first_cut_path_overlap_component_indices: $paired_replacement_prepare.barriered_first_cut_path_overlap_component_indices,
            paired_coplanar_candidate_replacement_barriered_second_cut_path_overlap_component_indices: $paired_replacement_prepare.barriered_second_cut_path_overlap_component_indices,
            paired_coplanar_candidate_replacement_barriered_first_cut_path_overlap_component_faces: $paired_replacement_prepare.barriered_first_cut_path_overlap_component_faces,
            paired_coplanar_candidate_replacement_barriered_second_cut_path_overlap_component_faces: $paired_replacement_prepare.barriered_second_cut_path_overlap_component_faces,
            paired_coplanar_candidate_replacement_fixed_barriered_first_prepare_part_dividable: $paired_replacement_prepare.fixed_barriered_first_prepare_part_dividable,
            paired_coplanar_candidate_replacement_fixed_barriered_second_prepare_part_dividable: $paired_replacement_prepare.fixed_barriered_second_prepare_part_dividable,
            paired_coplanar_candidate_replacement_fixed_barriered_prepare_first_face_indices: $paired_replacement_prepare.fixed_barriered_prepare_first_face_indices,
            paired_coplanar_candidate_replacement_fixed_barriered_prepare_second_face_indices: $paired_replacement_prepare.fixed_barriered_prepare_second_face_indices,
            paired_coplanar_candidate_replacement_fixed_barriered_first_cut_path_overlap_components: $paired_replacement_prepare.fixed_barriered_first_cut_path_overlap_components,
            paired_coplanar_candidate_replacement_fixed_barriered_second_cut_path_overlap_components: $paired_replacement_prepare.fixed_barriered_second_cut_path_overlap_components,
            paired_coplanar_candidate_first_replacement_cut_path_lengths: $paired_first_replacement_cut_path_inventory.path_lengths,
            paired_coplanar_candidate_second_replacement_cut_path_lengths: $paired_second_replacement_cut_path_inventory.path_lengths,
            paired_coplanar_candidate_first_replacement_closed_cut_path_lengths: $paired_first_replacement_cut_path_inventory.closed_path_lengths,
            paired_coplanar_candidate_second_replacement_closed_cut_path_lengths: $paired_second_replacement_cut_path_inventory.closed_path_lengths,
            paired_coplanar_candidate_first_replacement_closed_cut_path_source_faces: $paired_first_replacement_cut_path_inventory.closed_path_source_faces,
            paired_coplanar_candidate_second_replacement_closed_cut_path_source_faces: $paired_second_replacement_cut_path_inventory.closed_path_source_faces,
            paired_coplanar_candidate_first_replacement_closed_cut_path_source_face_runs: $paired_first_replacement_cut_path_inventory.closed_path_source_face_runs,
            paired_coplanar_candidate_second_replacement_closed_cut_path_source_face_runs: $paired_second_replacement_cut_path_inventory.closed_path_source_face_runs,
            paired_coplanar_candidate_first_replacement_closed_cut_path_edge_adjacent_source_faces: $paired_first_replacement_cut_path_inventory.closed_path_edge_adjacent_source_faces,
            paired_coplanar_candidate_second_replacement_closed_cut_path_edge_adjacent_source_faces: $paired_second_replacement_cut_path_inventory.closed_path_edge_adjacent_source_faces,
            paired_coplanar_candidate_first_replacement_closed_cut_path_edge_left_primary_source_faces: $paired_first_replacement_cut_path_inventory .closed_path_edge_left_primary_source_faces,
            paired_coplanar_candidate_second_replacement_closed_cut_path_edge_left_primary_source_faces: $paired_second_replacement_cut_path_inventory .closed_path_edge_left_primary_source_faces,
            paired_coplanar_candidate_first_replacement_closed_cut_path_edge_right_primary_source_faces: $paired_first_replacement_cut_path_inventory .closed_path_edge_right_primary_source_faces,
            paired_coplanar_candidate_second_replacement_closed_cut_path_edge_right_primary_source_faces: $paired_second_replacement_cut_path_inventory .closed_path_edge_right_primary_source_faces,
            paired_coplanar_candidate_first_replacement_closed_cut_path_edge_left_primary_source_face_runs: $paired_first_replacement_cut_path_inventory .closed_path_edge_left_primary_source_face_runs,
            paired_coplanar_candidate_second_replacement_closed_cut_path_edge_left_primary_source_face_runs: $paired_second_replacement_cut_path_inventory .closed_path_edge_left_primary_source_face_runs,
            paired_coplanar_candidate_first_replacement_closed_cut_path_edge_right_primary_source_face_runs: $paired_first_replacement_cut_path_inventory .closed_path_edge_right_primary_source_face_runs,
            paired_coplanar_candidate_second_replacement_closed_cut_path_edge_right_primary_source_face_runs: $paired_second_replacement_cut_path_inventory .closed_path_edge_right_primary_source_face_runs,
            paired_coplanar_candidate_first_replacement_meshlib_removed_face_owner_candidates: $paired_first_replacement_cut_path_inventory .closed_path_meshlib_removed_face_owner_candidates,
            paired_coplanar_candidate_second_replacement_meshlib_removed_face_owner_candidates: $paired_second_replacement_cut_path_inventory .closed_path_meshlib_removed_face_owner_candidates,
            paired_coplanar_candidate_first_replacement_meshlib_removed_face_owner_candidate_runs: $paired_first_replacement_cut_path_inventory .closed_path_meshlib_removed_face_owner_candidate_runs,
            paired_coplanar_candidate_second_replacement_meshlib_removed_face_owner_candidate_runs: $paired_second_replacement_cut_path_inventory .closed_path_meshlib_removed_face_owner_candidate_runs,
            paired_coplanar_candidate_meshlib_cut2origin_shadow_source_records: [ $paired_first_cut2origin_shadow_inventory.source_records, $paired_second_cut2origin_shadow_inventory.source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_unique_source_faces: [ $paired_first_cut2origin_shadow_inventory.unique_source_faces, $paired_second_cut2origin_shadow_inventory.unique_source_faces, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_duplicate_source_records: [ $paired_first_cut2origin_shadow_inventory.duplicate_source_records, $paired_second_cut2origin_shadow_inventory.duplicate_source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_split_source_records: [ $paired_first_cut2origin_shadow_inventory.split_source_records, $paired_second_cut2origin_shadow_inventory.split_source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_cut_event_source_records: [ $paired_first_cut2origin_shadow_inventory.cut_event_source_records, $paired_second_cut2origin_shadow_inventory.cut_event_source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_split_event_source_records: [ $paired_first_cut2origin_shadow_inventory.split_event_source_records, $paired_second_cut2origin_shadow_inventory.split_event_source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_prefill_repair_source_records: [ $paired_first_cut2origin_shadow_inventory.prefill_repair_source_records, $paired_second_cut2origin_shadow_inventory.prefill_repair_source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_open_edge_restoration_source_records: [ $paired_first_cut2origin_shadow_inventory.open_edge_restoration_source_records, $paired_second_cut2origin_shadow_inventory.open_edge_restoration_source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_orphan_repair_source_records: [ $paired_first_cut2origin_shadow_inventory.orphan_repair_source_records, $paired_second_cut2origin_shadow_inventory.orphan_repair_source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_fill_source_records: [ $paired_first_cut2origin_shadow_inventory.fill_source_records, $paired_second_cut2origin_shadow_inventory.fill_source_records, ],
            paired_coplanar_candidate_first_cut_path_lengths: $paired_first_cut_path_inventory .path_lengths,
            paired_coplanar_candidate_second_cut_path_lengths: $paired_second_cut_path_inventory .path_lengths,
            paired_coplanar_candidate_first_closed_cut_path_lengths: $paired_first_cut_path_inventory .closed_path_lengths,
            paired_coplanar_candidate_second_closed_cut_path_lengths: $paired_second_cut_path_inventory .closed_path_lengths,
            paired_coplanar_candidate_first_cut_path_source_faces: $paired_first_cut_path_inventory .path_source_faces,
            paired_coplanar_candidate_second_cut_path_source_faces: $paired_second_cut_path_inventory .path_source_faces,
            paired_coplanar_candidate_first_cut_path_source_face_runs: $paired_first_cut_path_inventory.path_source_face_runs,
            paired_coplanar_candidate_second_cut_path_source_face_runs: $paired_second_cut_path_inventory.path_source_face_runs,
            paired_coplanar_candidate_first_closed_cut_path_source_faces: $paired_first_cut_path_inventory.closed_path_source_faces,
            paired_coplanar_candidate_second_closed_cut_path_source_faces: $paired_second_cut_path_inventory.closed_path_source_faces,
            paired_coplanar_candidate_first_closed_cut_path_source_face_runs: $paired_first_cut_path_inventory.closed_path_source_face_runs,
            paired_coplanar_candidate_second_closed_cut_path_source_face_runs: $paired_second_cut_path_inventory.closed_path_source_face_runs,
            paired_coplanar_candidate_first_cut_path_edge_adjacent_source_faces: $paired_first_cut_path_inventory.path_edge_adjacent_source_faces,
            paired_coplanar_candidate_second_cut_path_edge_adjacent_source_faces: $paired_second_cut_path_inventory.path_edge_adjacent_source_faces,
            paired_coplanar_candidate_first_closed_cut_path_edge_adjacent_source_faces: $paired_first_cut_path_inventory.closed_path_edge_adjacent_source_faces,
            paired_coplanar_candidate_second_closed_cut_path_edge_adjacent_source_faces: $paired_second_cut_path_inventory.closed_path_edge_adjacent_source_faces,
            paired_coplanar_candidate_first_cut_path_edge_left_source_faces: $paired_first_cut_path_inventory.path_edge_left_source_faces,
            paired_coplanar_candidate_second_cut_path_edge_left_source_faces: $paired_second_cut_path_inventory.path_edge_left_source_faces,
            paired_coplanar_candidate_first_cut_path_edge_right_source_faces: $paired_first_cut_path_inventory.path_edge_right_source_faces,
            paired_coplanar_candidate_second_cut_path_edge_right_source_faces: $paired_second_cut_path_inventory.path_edge_right_source_faces,
            paired_coplanar_candidate_first_closed_cut_path_edge_left_source_faces: $paired_first_cut_path_inventory.closed_path_edge_left_source_faces,
            paired_coplanar_candidate_second_closed_cut_path_edge_left_source_faces: $paired_second_cut_path_inventory.closed_path_edge_left_source_faces,
            paired_coplanar_candidate_first_closed_cut_path_edge_right_source_faces: $paired_first_cut_path_inventory.closed_path_edge_right_source_faces,
            paired_coplanar_candidate_second_closed_cut_path_edge_right_source_faces: $paired_second_cut_path_inventory.closed_path_edge_right_source_faces,
            paired_coplanar_candidate_first_closed_cut_path_edge_left_primary_source_faces: $paired_first_cut_path_inventory.closed_path_edge_left_primary_source_faces,
            paired_coplanar_candidate_second_closed_cut_path_edge_left_primary_source_faces: $paired_second_cut_path_inventory.closed_path_edge_left_primary_source_faces,
            paired_coplanar_candidate_first_closed_cut_path_edge_right_primary_source_faces: $paired_first_cut_path_inventory.closed_path_edge_right_primary_source_faces,
            paired_coplanar_candidate_second_closed_cut_path_edge_right_primary_source_faces: $paired_second_cut_path_inventory.closed_path_edge_right_primary_source_faces,
            paired_coplanar_candidate_first_closed_cut_path_edge_left_primary_source_face_runs: $paired_first_cut_path_inventory.closed_path_edge_left_primary_source_face_runs,
            paired_coplanar_candidate_second_closed_cut_path_edge_left_primary_source_face_runs: $paired_second_cut_path_inventory.closed_path_edge_left_primary_source_face_runs,
            paired_coplanar_candidate_first_closed_cut_path_edge_right_primary_source_face_runs: $paired_first_cut_path_inventory.closed_path_edge_right_primary_source_face_runs,
            paired_coplanar_candidate_second_closed_cut_path_edge_right_primary_source_face_runs: $paired_second_cut_path_inventory.closed_path_edge_right_primary_source_face_runs,
            paired_coplanar_candidate_stitch_result_cut_path_lengths: $paired_stitch_result_cut_source_inventory.path_lengths,
            paired_coplanar_candidate_stitch_result_cut_edge_grouped_path_lengths: $paired_stitch_result_cut_source_inventory.edge_grouped_path_lengths,
            paired_coplanar_candidate_stitch_result_cut_edge_grouped_closed_paths: $paired_stitch_result_cut_source_inventory.edge_grouped_closed_paths,
            paired_coplanar_candidate_first_stitch_result_cut_path_source_faces: $paired_stitch_result_cut_source_inventory.first_path_source_faces,
            paired_coplanar_candidate_second_stitch_result_cut_path_source_faces: $paired_stitch_result_cut_source_inventory.second_path_source_faces,
            paired_coplanar_candidate_first_stitch_result_cut_path_source_face_runs: $paired_stitch_result_cut_source_inventory.first_path_source_face_runs,
            paired_coplanar_candidate_second_stitch_result_cut_path_source_face_runs: $paired_stitch_result_cut_source_inventory.second_path_source_face_runs,
            paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_candidates: $paired_stitch_result_cut_source_inventory .first_path_meshlib_removed_face_owner_candidates,
            paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_candidates: $paired_stitch_result_cut_source_inventory .second_path_meshlib_removed_face_owner_candidates,
            paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_candidate_runs: $paired_stitch_result_cut_source_inventory .first_path_meshlib_removed_face_owner_candidate_runs,
            paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_candidate_runs: $paired_stitch_result_cut_source_inventory .second_path_meshlib_removed_face_owner_candidate_runs,
            paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_path_source_faces: $paired_stitch_result_cut_source_inventory.first_edge_grouped_path_source_faces,
            paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_path_source_faces: $paired_stitch_result_cut_source_inventory.second_edge_grouped_path_source_faces,
            paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_path_source_face_runs: $paired_stitch_result_cut_source_inventory.first_edge_grouped_path_source_face_runs,
            paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_path_source_face_runs: $paired_stitch_result_cut_source_inventory.second_edge_grouped_path_source_face_runs,
            paired_coplanar_candidate_first_stitch_result_cut_source_faces: $paired_stitch_result_cut_source_inventory.first_source_faces,
            paired_coplanar_candidate_second_stitch_result_cut_source_faces: $paired_stitch_result_cut_source_inventory.second_source_faces,
            paired_coplanar_candidate_first_stitch_result_cut_source_face_runs: $paired_stitch_result_cut_source_inventory.first_source_face_runs,
            paired_coplanar_candidate_second_stitch_result_cut_source_face_runs: $paired_stitch_result_cut_source_inventory.second_source_face_runs,
            paired_coplanar_candidate_stitch_result_cut_missing_source_records: $paired_stitch_result_cut_source_inventory.missing_source_records,
            paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_source_faces: $paired_stitch_result_cut_source_inventory.first_meshlib_removed_face_owner_candidates,
            paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_source_faces: $paired_stitch_result_cut_source_inventory.second_meshlib_removed_face_owner_candidates,
            paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_source_face_runs: $paired_stitch_result_cut_source_inventory .first_meshlib_removed_face_owner_candidate_runs,
            paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_source_face_runs: $paired_stitch_result_cut_source_inventory .second_meshlib_removed_face_owner_candidate_runs,
            paired_coplanar_candidate_stitch_result_cut_meshlib_removed_face_owner_missing_records: $paired_stitch_result_cut_source_inventory .meshlib_removed_face_owner_candidate_missing_records,
            paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_source_faces: $paired_stitch_result_cut_source_inventory.first_edge_grouped_source_faces,
            paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_source_faces: $paired_stitch_result_cut_source_inventory.second_edge_grouped_source_faces,
            paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_source_face_runs: $paired_stitch_result_cut_source_inventory.first_edge_grouped_source_face_runs,
            paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_source_face_runs: $paired_stitch_result_cut_source_inventory.second_edge_grouped_source_face_runs,
            paired_coplanar_candidate_stitch_result_cut_edge_grouped_missing_source_records: $paired_stitch_result_cut_source_inventory.edge_grouped_missing_source_records,
            paired_coplanar_candidate_first_cut_source_face_counts: $paired_first_cut_inventory .source_face_counts,
            paired_coplanar_candidate_second_cut_source_face_counts: $paired_second_cut_inventory .source_face_counts,
            paired_coplanar_candidate_first_replacement_cut_source_face_counts: $paired_first_replacement_cut_inventory.source_face_counts,
            paired_coplanar_candidate_second_replacement_cut_source_face_counts: $paired_second_replacement_cut_inventory.source_face_counts,
            paired_coplanar_candidate_first_shadow_repaired_replacement_cut_source_face_counts: $paired_first_shadow_repaired_replacement_cut_inventory.source_face_counts,
            paired_coplanar_candidate_second_shadow_repaired_replacement_cut_source_face_counts: $paired_second_shadow_repaired_replacement_cut_inventory.source_face_counts,
            paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_cut_source_face_counts: $paired_first_owner_remapped_shadow_repaired_replacement_cut_inventory.source_face_counts,
            paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_cut_source_face_counts: $paired_second_owner_remapped_shadow_repaired_replacement_cut_inventory.source_face_counts,
            paired_coplanar_candidate_first_replacement_fill_plan_source_faces: $paired_first_replacement_cut_inventory.fill_plan_source_faces,
            paired_coplanar_candidate_second_replacement_fill_plan_source_faces: $paired_second_replacement_cut_inventory.fill_plan_source_faces,
            paired_coplanar_candidate_first_replacement_fill_plan_added_faces: $paired_first_replacement_cut_inventory.fill_plan_added_faces,
            paired_coplanar_candidate_second_replacement_fill_plan_added_faces: $paired_second_replacement_cut_inventory.fill_plan_added_faces,
            paired_coplanar_candidate_first_shadow_repaired_replacement_fill_plan_source_faces: $paired_first_shadow_repaired_replacement_cut_inventory.fill_plan_source_faces,
            paired_coplanar_candidate_second_shadow_repaired_replacement_fill_plan_source_faces: $paired_second_shadow_repaired_replacement_cut_inventory.fill_plan_source_faces,
            paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_fill_plan_source_faces: $paired_first_owner_remapped_shadow_repaired_replacement_cut_inventory .fill_plan_source_faces,
            paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_fill_plan_source_faces: $paired_second_owner_remapped_shadow_repaired_replacement_cut_inventory .fill_plan_source_faces,
            paired_coplanar_candidate_first_shadow_repaired_replacement_fill_plan_added_faces: $paired_first_shadow_repaired_replacement_cut_inventory.fill_plan_added_faces,
            paired_coplanar_candidate_second_shadow_repaired_replacement_fill_plan_added_faces: $paired_second_shadow_repaired_replacement_cut_inventory.fill_plan_added_faces,
            paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_fill_plan_added_faces: $paired_first_owner_remapped_shadow_repaired_replacement_cut_inventory .fill_plan_added_faces,
            paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_fill_plan_added_faces: $paired_second_owner_remapped_shadow_repaired_replacement_cut_inventory .fill_plan_added_faces,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_source_face_counts: $paired_first_cut2origin_shadow_inventory.source_face_counts,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_source_face_counts: $paired_second_cut2origin_shadow_inventory.source_face_counts,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_source_face_runs: $paired_first_cut2origin_shadow_inventory.source_face_runs,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_source_face_runs: $paired_second_cut2origin_shadow_inventory.source_face_runs,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_source_faces: $paired_first_cut2origin_shadow_inventory.source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_source_faces: $paired_second_cut2origin_shadow_inventory.source_face_sequence,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_appended_source_faces: $paired_first_cut2origin_shadow_inventory.appended_source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_appended_source_faces: $paired_second_cut2origin_shadow_inventory.appended_source_face_sequence,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_appended_source_face_runs: $paired_first_cut2origin_shadow_inventory.appended_source_face_runs,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_appended_source_face_runs: $paired_second_cut2origin_shadow_inventory.appended_source_face_runs,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_prefill_repair_record_details: $paired_first_cut2origin_shadow_inventory.prefill_repair_record_details,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_prefill_repair_record_details: $paired_second_cut2origin_shadow_inventory.prefill_repair_record_details,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_open_edge_restoration_record_details: $paired_first_cut2origin_shadow_inventory.open_edge_restoration_record_details,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_open_edge_restoration_record_details: $paired_second_cut2origin_shadow_inventory.open_edge_restoration_record_details,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_orphan_repair_record_details: $paired_first_cut2origin_shadow_inventory.orphan_repair_record_details,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_orphan_repair_record_details: $paired_second_cut2origin_shadow_inventory.orphan_repair_record_details,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_split_source_faces: $paired_first_cut2origin_shadow_inventory.split_appended_source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_split_source_faces: $paired_second_cut2origin_shadow_inventory.split_appended_source_face_sequence,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_cut_event_source_faces: $paired_first_cut2origin_shadow_inventory.cut_event_source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_cut_event_source_faces: $paired_second_cut2origin_shadow_inventory.cut_event_source_face_sequence,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_split_event_source_faces: $paired_first_cut2origin_shadow_inventory.split_event_source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_split_event_source_faces: $paired_second_cut2origin_shadow_inventory.split_event_source_face_sequence,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_prefill_repair_source_faces: $paired_first_cut2origin_shadow_inventory.prefill_repair_source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_prefill_repair_source_faces: $paired_second_cut2origin_shadow_inventory.prefill_repair_source_face_sequence,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_open_edge_restoration_source_faces: $paired_first_cut2origin_shadow_inventory.open_edge_restoration_source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_open_edge_restoration_source_faces: $paired_second_cut2origin_shadow_inventory.open_edge_restoration_source_face_sequence,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_orphan_repair_source_faces: $paired_first_cut2origin_shadow_inventory.orphan_repair_source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_orphan_repair_source_faces: $paired_second_cut2origin_shadow_inventory.orphan_repair_source_face_sequence,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_fill_source_faces: $paired_first_cut2origin_shadow_inventory.fill_appended_source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_fill_source_faces: $paired_second_cut2origin_shadow_inventory.fill_appended_source_face_sequence,
            paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_ready: [ $paired_first_cut2origin_shadow_owner_remap.ready, $paired_second_cut2origin_shadow_owner_remap.ready, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_source_records: [ $paired_first_cut2origin_shadow_owner_remap.source_records, $paired_second_cut2origin_shadow_owner_remap.source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_matching_source_records: [ $paired_first_cut2origin_shadow_owner_remap.matching_source_records, $paired_second_cut2origin_shadow_owner_remap.matching_source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_mismatched_source_records: [ $paired_first_cut2origin_shadow_owner_remap.mismatched_source_records, $paired_second_cut2origin_shadow_owner_remap.mismatched_source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_missing_materialized_source_records: [ $paired_first_cut2origin_shadow_owner_remap.missing_materialized_source_records, $paired_second_cut2origin_shadow_owner_remap.missing_materialized_source_records, ],
            paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_extra_materialized_source_records: [ $paired_first_cut2origin_shadow_owner_remap.extra_materialized_source_records, $paired_second_cut2origin_shadow_owner_remap.extra_materialized_source_records, ],
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_source_faces: $paired_first_cut2origin_shadow_owner_remap.source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_source_faces: $paired_second_cut2origin_shadow_owner_remap.source_face_sequence,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_appended_source_faces: $paired_first_cut2origin_shadow_owner_remap.appended_source_face_sequence,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_appended_source_faces: $paired_second_cut2origin_shadow_owner_remap.appended_source_face_sequence,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_source_face_counts: $paired_first_cut2origin_shadow_owner_remap.source_face_counts,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_source_face_counts: $paired_second_cut2origin_shadow_owner_remap.source_face_counts,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_source_face_runs: $paired_first_cut2origin_shadow_owner_remap.source_face_runs,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_source_face_runs: $paired_second_cut2origin_shadow_owner_remap.source_face_runs,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_appended_source_face_runs: $paired_first_cut2origin_shadow_owner_remap.appended_source_face_runs,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_appended_source_face_runs: $paired_second_cut2origin_shadow_owner_remap.appended_source_face_runs,
            paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_mismatch_details: $paired_first_cut2origin_shadow_owner_remap.mismatch_details,
            paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_mismatch_details: $paired_second_cut2origin_shadow_owner_remap.mismatch_details,
            paired_coplanar_candidate_first_meshlib_valid_cut_faces: $paired_first_meshlib_valid_cut_faces,
            paired_coplanar_candidate_second_meshlib_valid_cut_faces: $paired_second_meshlib_valid_cut_faces,
            paired_coplanar_candidate_prepared_base_record_rewrite: $paired_coplanar_candidate_prepared_base_record_rewrite,
            paired_coplanar_candidate_replacement_prepared_base_record_rewrite: $paired_replacement_prepare.prepared_base_record_rewrite,
            paired_coplanar_candidate_replacement_barriered_prepared_base_record_rewrite: $paired_replacement_prepare.barriered_prepared_base_record_rewrite,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_prepared_base_record_rewrite: $paired_owner_remapped_shadow_repaired_replacement_prepare.prepared_base_record_rewrite,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_barriered_prepared_base_record_rewrite: $paired_owner_remapped_shadow_repaired_replacement_prepare .barriered_prepared_base_record_rewrite,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_prepare_first_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_prepare_first_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_prepare_second_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_prepare_second_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_first_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_selected_first_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_second_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_selected_second_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_first_component_summaries: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_first_component_summaries,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_second_component_summaries: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_second_component_summaries,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_first_component_faces: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_first_component_faces,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_second_component_faces: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_second_component_faces,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_fixed_barriered_first_prepare_part_dividable: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_fixed_barriered_first_prepare_part_dividable,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_fixed_barriered_second_prepare_part_dividable: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_fixed_barriered_second_prepare_part_dividable,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_fixed_barriered_selected_first_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_fixed_barriered_selected_first_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_fixed_barriered_selected_second_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_fixed_barriered_selected_second_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_no_contact_barrier_first_prepare_part_dividable: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_no_contact_barrier_first_prepare_part_dividable,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_no_contact_barrier_second_prepare_part_dividable: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_no_contact_barrier_second_prepare_part_dividable,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_no_contact_barrier_selected_first_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_no_contact_barrier_selected_first_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_no_contact_barrier_selected_second_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_no_contact_barrier_selected_second_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_prepare_first_added_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_prepare_first_added_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_prepare_second_added_face_indices: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_prepare_second_added_face_indices,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_prepared_base_record_rewrite: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_prepared_base_record_rewrite,
            paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_added_fill_prepared_base_record_rewrite: $paired_owner_remapped_shadow_repaired_replacement_prepare .slot_projected_barriered_added_fill_prepared_base_record_rewrite,
            paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_lifecycle_coverage: $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_selected_lifecycle_coverage,
            paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_lifecycle_coverage: $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_selected_lifecycle_coverage,
            paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_lifecycle_export_coverage: $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_lifecycle_export_coverage,
            paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_lifecycle_export_coverage: $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_lifecycle_export_coverage,
            paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_added_fill_lifecycle_export_coverage: $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_added_fill_lifecycle_export_coverage,
            paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_added_fill_lifecycle_export_coverage: $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_added_fill_lifecycle_export_coverage,
            paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_lifecycle_slots: $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_selected_lifecycle_slots,
            paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_lifecycle_slots: $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_selected_lifecycle_slots,
            paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_lifecycle_export_slots: $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_lifecycle_export_slots,
            paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_lifecycle_export_slots: $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_lifecycle_export_slots,
            paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_added_fill_lifecycle_export_slots: $paired_first_owner_remapped_shadow_repaired_replacement_slot_projected_added_fill_lifecycle_export_slots,
            paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_added_fill_lifecycle_export_slots: $paired_second_owner_remapped_shadow_repaired_replacement_slot_projected_added_fill_lifecycle_export_slots,
            coplanar_cut_trial_first_skipped_faces: $input .coplanar_cut_trial .map(|trial| trial.first_skipped_source_faces.clone()) .unwrap_or_default(),
            coplanar_cut_trial_second_skipped_faces: $input .coplanar_cut_trial .map(|trial| trial.second_skipped_source_faces.clone()) .unwrap_or_default(),
            coplanar_cut_trial_accepted: $input .coplanar_cut_trial .map(|trial| trial.accepted) .unwrap_or_default(),
            stitched_output_edges: $input.topology_splice_plan.entries.len(),
            stitched_output_edges_with_two_faces: $input.topology_splice_plan.manifold_edges,
            stitched_output_edges_needing_splice: $input.topology_splice_plan.boundary_edges,
            topology_splice_ready: $input.topology_splice_plan.ready_for_splice,
            topology_splice_missing_edges: $input.topology_splice_plan.missing_edges,
            topology_splice_non_manifold_edges: $input.topology_splice_plan.non_manifold_edges,
            topology_splice_apply_ready: $input.topology_splice_apply_plan.ready_for_mutation,
            topology_splice_verified_boundary_edges: $input .topology_splice_apply_plan .verified_boundary_edges,
            topology_splice_blocked_edges: $input.topology_splice_apply_plan.blocked_edges,
            topology_splice_failed_edges: $input.topology_splice_apply_plan.failed_edges,
            topology_splice_synthetic_side_edges: $input.topology_splice_apply_plan.synthetic_side_edges,
            topology_splice_materialized_boundary_edges: $input .topology_splice_apply_plan .materialized_boundary_edges,
            topology_splice_materialization_failed_edges: $input .topology_splice_apply_plan .materialization_failed_edges,
            topology_splice_exported_faces: $input.topology_splice_apply_plan.exported_faces,
            topology_splice_export_failed_faces: $input.topology_splice_apply_plan.export_failed_faces,
            topology_splice_edges_before_materialization: $input .topology_splice_apply_plan .topology_edges_before_materialization,
            topology_splice_edges_after_materialization: $input .topology_splice_apply_plan .topology_edges_after_materialization,
            topology_splice_deleted_synthetic_edges: $input .topology_splice_apply_plan .deleted_synthetic_stitch_edges,
            topology_splice_export_changed_faces: $topology_splice_export_changed_faces,
            topology_splice_duplicated_output_edges: $input .topology_splice_apply_plan .duplicated_output_topology_edges,
            topology_splice_duplicate_output_face_groups: $duplicate_output_face_groups,
            topology_splice_duplicate_output_faces: $duplicate_output_faces,
            meshlib_topology_base_faces: $meshlib.topology_rewrite.base_faces,
            meshlib_topology_incoming_faces: $meshlib.topology_rewrite.incoming_faces,
            meshlib_topology_selected_first_faces: $face_source_summary.selected_first_faces,
            meshlib_topology_selected_second_faces: $face_source_summary.selected_second_faces,
            meshlib_topology_raw_selected_faces: $raw_face_selection_summary.raw_selected_faces,
            meshlib_topology_same_oriented_overlap_faces: $raw_face_selection_summary.overlap_faces,
            meshlib_topology_boundary_misses: $raw_face_selection_summary.boundary_misses,
            meshlib_topology_coplanar_selection_delta_faces: $raw_face_selection_summary .selection_delta_faces,
            meshlib_topology_first_source_face_groups: $face_source_summary.first_source_face_groups,
            meshlib_topology_second_source_face_groups: $face_source_summary.second_source_face_groups,
            meshlib_topology_duplicate_first_source_faces: $face_source_summary .duplicate_first_source_faces,
            meshlib_topology_duplicate_second_source_faces: $face_source_summary .duplicate_second_source_faces,
            meshlib_topology_mapped_contour_edges: $meshlib.topology_rewrite.mapped_contour_edges,
            meshlib_topology_missing_base_edges: $meshlib.topology_rewrite.missing_base_contour_edges,
            meshlib_topology_missing_incoming_edges: $meshlib .topology_rewrite .missing_incoming_contour_edges,
            meshlib_topology_direction_mismatches: $meshlib .topology_rewrite .contour_direction_mismatches,
            meshlib_topology_mapped_stitch_contour_edges: $meshlib .topology_rewrite .mapped_stitch_contour_edges,
            meshlib_topology_missing_stitch_contour_edges: $meshlib .topology_rewrite .missing_stitch_contour_edges,
            meshlib_topology_synthetic_stitch_contour_edges: $meshlib .topology_rewrite .synthetic_stitch_contour_edges,
            meshlib_topology_stitch_direction_mismatches: $meshlib .topology_rewrite .stitch_direction_mismatches,
            meshlib_topology_stitch_metadata_ready: $input.stitch_plan.compatible && $input.assembly.result_cut_paths_complete && $meshlib.topology_rewrite.stitch_metadata_ready,
            meshlib_topology_materialized_stitch_contour_edges: $meshlib .topology_rewrite .materialized_stitch_contour_edges,
            meshlib_topology_unmaterialized_stitch_contour_edges: $meshlib .topology_rewrite .unmaterialized_stitch_contour_edges,
            meshlib_topology_materialized_synthetic_stitch_sides: $meshlib .topology_rewrite .materialized_synthetic_stitch_sides,
            meshlib_topology_stitch_materialization_direction_mismatches: $meshlib .topology_rewrite .stitch_materialization_direction_mismatches,
            meshlib_topology_stitch_materialization_ready: $input.stitch_plan.compatible && $input.assembly.result_cut_paths_complete && $meshlib.topology_rewrite.stitch_materialization_ready,
            meshlib_topology_record_rewrite_commands: $meshlib.topology_rewrite.record_rewrite_commands,
            meshlib_topology_record_rewrite_blocked_edges: $meshlib .topology_rewrite .record_rewrite_blocked_edges,
            meshlib_topology_record_rewrite_synthetic_sides: $meshlib .topology_rewrite .record_rewrite_synthetic_sides,
            meshlib_topology_record_rewrite_direction_mismatches: $meshlib .topology_rewrite .record_rewrite_direction_mismatches,
            meshlib_topology_record_rewrite_ready: $input.stitch_plan.compatible && $input.assembly.result_cut_paths_complete && $meshlib.topology_rewrite.record_rewrite_ready,
            meshlib_topology_copied_edge_prepared_faces: $meshlib.copied_edges.prepared_faces,
            meshlib_topology_copied_edge_prepared_vertices: $meshlib.copied_edges.prepared_vertices,
            meshlib_topology_virtual_copied_vertices: $meshlib.copied_edges.virtual_copied_vertices,
            meshlib_topology_copied_edge_prepared_edges: $meshlib.copied_edges.prepared_edges,
            meshlib_topology_copied_edge_mapped_edges: $meshlib.copied_edges.mapped_edges,
            meshlib_topology_copied_edges: $meshlib.copied_edges.copied_edges,
            meshlib_topology_copied_edges_mapped_to_existing_output: $meshlib .copied_edges .copied_edges_mapped_to_existing_output,
            meshlib_topology_copied_edges_mapped_to_output: $meshlib .copied_edges .copied_edges_mapped_to_output,
            meshlib_topology_copied_edges_missing_output_vertices: $meshlib .copied_edges .copied_edges_missing_output_vertices,
            meshlib_topology_copied_edge_translation_ready: $meshlib .copied_edges .ready_for_record_translation(),
            meshlib_topology_open_stitch_paths: $meshlib.topology_rewrite.open_stitch_paths,
            meshlib_topology_open_stitch_near_edge_updates: $meshlib .topology_rewrite .open_stitch_near_edge_updates,
            meshlib_topology_open_stitch_near_edge_blocked_updates: $meshlib .topology_rewrite .open_stitch_near_edge_blocked_updates,
            meshlib_topology_open_stitch_near_edge_ready: $input.stitch_plan.compatible && $input.assembly.result_cut_paths_complete && $meshlib.topology_rewrite.open_stitch_near_edge_ready,
            meshlib_topology_near_stitch_update_commands: $meshlib .record_rewrite_apply .near_stitch_update_commands,
            meshlib_topology_near_stitch_updates_applied: $meshlib .record_rewrite_apply .applied_near_stitch_updates,
            meshlib_topology_near_stitch_updates_failed: $meshlib .record_rewrite_apply .failed_near_stitch_updates,
            meshlib_topology_near_stitch_updates_failed_start: $meshlib .record_rewrite_apply .failed_near_stitch_start_updates,
            meshlib_topology_near_stitch_updates_failed_end: $meshlib .record_rewrite_apply .failed_near_stitch_end_updates,
            meshlib_topology_near_stitch_updates_missing_previous_edges: $meshlib .record_rewrite_apply .failed_missing_near_stitch_previous_edges,
            meshlib_topology_near_stitch_updates_missing_next_edges: $meshlib .record_rewrite_apply .failed_missing_near_stitch_next_edges,
            meshlib_topology_near_stitch_updates_origin_mismatches: $meshlib .record_rewrite_apply .failed_near_stitch_origin_mismatches,
            meshlib_topology_near_stitch_updates_previous_left_faces: $meshlib .record_rewrite_apply .failed_near_stitch_previous_left_faces,
            meshlib_topology_near_stitch_updates_next_right_faces: $meshlib .record_rewrite_apply .failed_near_stitch_next_right_faces,
            meshlib_topology_near_stitch_updates_failed_other: $meshlib .record_rewrite_apply .failed_other_near_stitch_updates,
            meshlib_topology_near_stitch_failed_details: $meshlib::near_stitch_failure_details( &$meshlib.record_rewrite_apply, ),
            meshlib_topology_record_rewrite_applied_commands: $meshlib .record_rewrite_apply .applied_commands,
            meshlib_topology_record_rewrite_failed_commands: $meshlib .record_rewrite_apply .failed_commands,
            meshlib_topology_record_rewrite_failed_missing_targets: $meshlib .record_rewrite_apply .failed_missing_target_edges,
            meshlib_topology_record_rewrite_failed_closed_targets: $meshlib .record_rewrite_apply .failed_closed_target_edges,
            meshlib_topology_record_rewrite_failed_missing_sources: $meshlib .record_rewrite_apply .failed_missing_source_edges,
            meshlib_topology_record_rewrite_failed_other_commands: $meshlib .record_rewrite_apply .failed_other_commands,
            meshlib_topology_record_rewrite_prepared_synthetic_targets: $meshlib .record_rewrite_apply .prepared_synthetic_target_edges,
            meshlib_topology_record_rewrite_translated_face_records: $meshlib .record_rewrite_apply .translated_face_records,
            meshlib_topology_record_rewrite_apply_synthetic_sides: $meshlib .record_rewrite_apply .synthetic_side_edges,
            meshlib_topology_record_rewrite_exported_faces: $meshlib.record_rewrite_apply.exported_faces,
            meshlib_topology_record_rewrite_export_failed_faces: $meshlib .record_rewrite_apply .export_failed_faces,
            meshlib_topology_record_rewrite_export_non_triangular_faces: $meshlib .record_rewrite_apply .export_non_triangular_faces,
            meshlib_topology_record_rewrite_export_left_ring_not_closed_faces: $meshlib .record_rewrite_apply .export_left_ring_not_closed_faces,
            meshlib_topology_record_rewrite_export_missing_origin_faces: $meshlib .record_rewrite_apply .export_missing_origin_faces,
            meshlib_topology_record_rewrite_export_other_failed_faces: $meshlib .record_rewrite_apply .export_other_failed_faces,
            meshlib_topology_record_rewrite_export_changed_faces: $meshlib .record_rewrite_apply .export_changed_faces,
            meshlib_topology_record_rewrite_apply_ready: $input.stitch_plan.compatible && $input.assembly.result_cut_paths_complete && $meshlib.topology_rewrite.record_rewrite_ready && $meshlib.near_stitch.blocked_updates == 0 && $meshlib.record_rewrite_apply.ready_for_export,
            meshlib_topology_record_rewrite_exported_mesh_stats: $meshlib .record_rewrite_exported_mesh_stats,
            meshlib_topology_record_rewrite_exported_mesh_health: $meshlib .record_rewrite_exported_mesh_health,
            meshlib_topology_record_rewrite_packed_mesh_stats: $meshlib.record_rewrite_packed_mesh_stats,
            meshlib_topology_record_rewrite_packed_mesh_health: $meshlib .record_rewrite_packed_mesh_health,
            meshlib_topology_prepared_base_record_rewrite: $meshlib.prepared_base_record_rewrite,
            meshlib_topology_rewrite_ready: $input.stitch_plan.compatible && $input.assembly.result_cut_paths_complete && $meshlib.topology_rewrite.ready_for_rewrite,
            output_mesh_stats: $output_mesh_stats,
            output_mesh_health: $output_mesh_health,
            output_mesh_source: $input.output.source,
            topology_splice_exported_mesh_stats: $topology_splice_exported_mesh_stats,
            topology_splice_exported_mesh_health: $topology_splice_exported_mesh_health,
            output_faces: $input.output.faces.len(),
            result_cut_paths: $result_cut_summary.paths,
            result_cut_path_edges: $result_cut_summary.path_edges,
            result_cut_closed_paths: $result_cut_summary.closed_paths,
            result_cut_mapped_paths: $input.assembly.result_cut_paths.len(),
            result_cut_mapped_path_edges: $input.assembly.result_cut_paths.iter().map(Vec::len).sum(),
            result_cut_mapped_closed_paths: $input .assembly .result_cut_path_closed .iter() .filter(|&&is_closed| is_closed) .count(),
            result_cut_paths_complete: $input.assembly.result_cut_paths_complete,
            parity_ready: $parity_ready,
        })
    };
}
