use super::super::exact_boolean::ExactBooleanOutputMeshSource;
use super::meshlib::{
    MeshlibNearStitchFailureDiagnostic, MeshlibPreparedBaseRecordRewriteDiagnostics,
};
use crate::{MeshHealth, MeshStats};

#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
pub struct ExactBooleanPipelineDiagnostics {
    pub first_cut_edges: usize,
    pub second_cut_edges: usize,
    pub first_skipped_source_faces: Vec<usize>,
    pub second_skipped_source_faces: Vec<usize>,
    pub first_fill_plans: usize,
    pub second_fill_plans: usize,
    pub stitch_compatible: bool,
    pub stitch_unmatched_first_edges: usize,
    pub stitch_unmatched_second_edges: usize,
    pub stitch_cut_path_length_mismatches: usize,
    pub requires_topology_splice: bool,
    pub first_vertices_mixed_against_second: bool,
    pub second_vertices_mixed_against_first: bool,
    pub possible_missing_cut_intersections: bool,
    pub first_prepare_part_dividable: bool,
    pub second_prepare_part_dividable: bool,
    pub first_cut_path_side_components: [usize; 2],
    pub second_cut_path_side_components: [usize; 2],
    pub first_cut_path_overlap_components: usize,
    pub second_cut_path_overlap_components: usize,
    pub coplanar_overlap_pairs: usize,
    pub coplanar_overlap_region_edges: usize,
    pub coplanar_overlap_area: f64,
    pub coplanar_overlap_contours: usize,
    pub coplanar_overlap_contour_edges: usize,
    pub coplanar_cut_trial_contours: usize,
    pub coplanar_cut_trial_contour_edges: usize,
    pub coplanar_cut_trial_first_cut_edges: usize,
    pub coplanar_cut_trial_second_cut_edges: usize,
    pub paired_coplanar_cut_trial_contours: usize,
    pub paired_coplanar_cut_trial_contour_edges: usize,
    pub paired_coplanar_cut_trial_first_cut_edges: usize,
    pub paired_coplanar_cut_trial_second_cut_edges: usize,
    pub paired_coplanar_combined_first_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_combined_second_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_combined_first_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_combined_second_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_combined_first_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_first_collapsed_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_combined_second_collapsed_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_combined_first_collapsed_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_combined_second_collapsed_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_combined_first_collapsed_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_collapsed_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_first_source_preserving_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_combined_second_source_preserving_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_combined_first_source_preserving_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_combined_second_source_preserving_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_combined_first_source_preserving_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_source_preserving_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_first_source_preserving_cut_path_collapsed: Vec<Vec<bool>>,
    pub paired_coplanar_combined_second_source_preserving_cut_path_collapsed: Vec<Vec<bool>>,
    pub paired_coplanar_combined_first_source_preserving_cut_path_start_primitive_kinds: Vec<Vec<usize>>,
    pub paired_coplanar_combined_second_source_preserving_cut_path_start_primitive_kinds: Vec<Vec<usize>>,
    pub paired_coplanar_combined_first_source_preserving_cut_path_start_primitive_faces: Vec<Vec<i64>>,
    pub paired_coplanar_combined_second_source_preserving_cut_path_start_primitive_faces: Vec<Vec<i64>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_order_rotations: Vec<usize>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_order_rotations: Vec<usize>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_cut_path_start_primitive_faces: Vec<Vec<i64>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_cut_path_start_primitive_faces: Vec<Vec<i64>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_cut_path_collapsed: Vec<Vec<bool>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_cut_path_collapsed: Vec<Vec<bool>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_cut_edge_paths: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_cut_edge_paths: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_removed_face_owner_candidates: Vec<Vec<usize>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_removed_face_owner_candidates: Vec<Vec<usize>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_collapsed_removed_face_owner_candidates: Vec<Vec<usize>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_collapsed_removed_face_owner_candidates: Vec<Vec<usize>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_collapsed_removed_face_owner_candidate_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_collapsed_removed_face_owner_candidate_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_removed_face_owner_candidate_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_removed_face_owner_candidate_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_replacement_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_replacement_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_replacement_source_face_counts: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_replacement_source_face_counts: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_replacement_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_replacement_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_replacement_lifecycle_runs: Vec<Vec<[usize; 4]>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_replacement_lifecycle_runs: Vec<Vec<[usize; 4]>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_replacement_lifecycle_slot_runs: Vec<Vec<[usize; 8]>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_replacement_lifecycle_slot_runs: Vec<Vec<[usize; 8]>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_cut2origin_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_cut2origin_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_cut2origin_source_face_counts: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_cut2origin_source_face_counts: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_vs_source_preserving_source_face_count_deltas: Vec<[i64; 2]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_vs_source_preserving_source_face_count_deltas: Vec<[i64; 2]>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_like_cut2origin_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_like_cut2origin_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_removed_face_owner_candidates: Vec<Vec<usize>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_removed_face_owner_candidates: Vec<Vec<usize>>,
    pub paired_coplanar_combined_first_source_preserving_meshlib_removed_face_owner_candidate_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_second_source_preserving_meshlib_removed_face_owner_candidate_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_combined_source_preserving_meshlib_removed_face_owner_missing_records: [usize; 2],
    pub paired_coplanar_combined_duplicate_first_path_edge_occurrences: usize,
    pub paired_coplanar_combined_duplicate_second_path_edge_occurrences: usize,
    pub paired_coplanar_combined_duplicate_first_path_edge_path_indices: Vec<Vec<usize>>,
    pub paired_coplanar_combined_duplicate_second_path_edge_path_indices: Vec<Vec<usize>>,
    pub paired_coplanar_stitch_cut_path_length_mismatches: usize,
    pub paired_coplanar_stitch_unmatched_first_edges: usize,
    pub paired_coplanar_stitch_unmatched_second_edges: usize,
    pub paired_coplanar_duplicate_first_path_edges: usize,
    pub paired_coplanar_duplicate_second_path_edges: usize,
    pub paired_coplanar_duplicate_first_path_edge_occurrences: usize,
    pub paired_coplanar_duplicate_second_path_edge_occurrences: usize,
    pub paired_coplanar_duplicate_first_path_edge_path_indices: Vec<Vec<usize>>,
    pub paired_coplanar_duplicate_second_path_edge_path_indices: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_stitch_compatible: bool,
    pub paired_coplanar_candidate_first_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_second_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_prepare_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_prepare_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_selected_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_selected_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_first_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_replacement_second_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_replacement_prepare_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_prepare_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_selected_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_selected_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_first_cut_path_side_components: [usize; 2],
    pub paired_coplanar_candidate_replacement_second_cut_path_side_components: [usize; 2],
    pub paired_coplanar_candidate_replacement_first_cut_path_overlap_components: usize,
    pub paired_coplanar_candidate_replacement_second_cut_path_overlap_components: usize,
    pub paired_coplanar_candidate_replacement_first_cut_path_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_second_cut_path_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_first_cut_path_left_component_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_second_cut_path_left_component_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_first_cut_path_right_component_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_second_cut_path_right_component_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_first_cut_path_overlap_component_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_second_cut_path_overlap_component_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_first_cut_path_left_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_second_cut_path_left_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_first_cut_path_right_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_second_cut_path_right_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_first_cut_path_overlap_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_second_cut_path_overlap_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_result_cut_paths_complete: bool,
    pub paired_coplanar_candidate_replacement_prepare_cut_complete: bool,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_first_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_second_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_result_cut_paths_complete: bool,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_prepare_cut_complete: bool,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_prepare_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_prepare_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_selected_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_selected_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_first_cut_path_side_components: [usize; 2],
    pub paired_coplanar_candidate_second_cut_path_side_components: [usize; 2],
    pub paired_coplanar_candidate_first_cut_path_overlap_components: usize,
    pub paired_coplanar_candidate_second_cut_path_overlap_components: usize,
    pub paired_coplanar_candidate_result_cut_paths_complete: bool,
    pub paired_coplanar_candidate_prepare_cut_complete: bool,
    pub paired_coplanar_candidate_output_faces: usize,
    pub paired_coplanar_candidate_output_area: f64,
    pub paired_coplanar_candidate_output_volume: f64,
    pub paired_coplanar_candidate_self_intersections: Option<usize>,
    pub paired_coplanar_candidate_self_intersections_available: bool,
    pub paired_coplanar_candidate_active_volume_delta: f64,
    pub paired_coplanar_candidate_preserves_active_volume: bool,
    pub paired_coplanar_candidate_boundary_edges: usize,
    pub paired_coplanar_candidate_nonmanifold_edges: usize,
    pub paired_coplanar_candidate_duplicate_output_faces: usize,
    pub paired_coplanar_candidate_meshlib_base_faces: usize,
    pub paired_coplanar_candidate_meshlib_incoming_faces: usize,
    pub paired_coplanar_candidate_meshlib_base_vertices: usize,
    pub paired_coplanar_candidate_meshlib_incoming_vertices: usize,
    pub paired_coplanar_candidate_meshlib_unstitched_faces: usize,
    pub paired_coplanar_candidate_meshlib_unstitched_vertices: usize,
    pub paired_coplanar_candidate_meshlib_path_pairs: usize,
    pub paired_coplanar_candidate_meshlib_path_count_mismatch: bool,
    pub paired_coplanar_candidate_meshlib_path_length_mismatches: usize,
    pub paired_coplanar_candidate_meshlib_path_closed_mismatches: usize,
    pub paired_coplanar_candidate_meshlib_path_coordinate_mismatches: usize,
    pub paired_coplanar_candidate_meshlib_path_same_direction_edges: usize,
    pub paired_coplanar_candidate_meshlib_path_reversed_edges: usize,
    pub paired_coplanar_candidate_meshlib_base_mapped_cut_path_edges: usize,
    pub paired_coplanar_candidate_meshlib_incoming_mapped_cut_path_edges: usize,
    pub paired_coplanar_candidate_meshlib_base_missing_cut_path_edges: usize,
    pub paired_coplanar_candidate_meshlib_incoming_missing_cut_path_edges: usize,
    pub paired_coplanar_candidate_meshlib_base_cut_paths_complete: bool,
    pub paired_coplanar_candidate_meshlib_incoming_cut_paths_complete: bool,
    pub paired_coplanar_candidate_cut_faces: [usize; 2],
    pub paired_coplanar_candidate_cut_source_records: [usize; 2],
    pub paired_coplanar_candidate_cut_unique_source_faces: [usize; 2],
    pub paired_coplanar_candidate_cut_duplicate_source_records: [usize; 2],
    pub paired_coplanar_candidate_cut_fill_plans: [usize; 2],
    pub paired_coplanar_candidate_cut_added_faces: [usize; 2],
    pub paired_coplanar_candidate_replacement_cut_faces: [usize; 2],
    pub paired_coplanar_candidate_replacement_cut_source_records: [usize; 2],
    pub paired_coplanar_candidate_replacement_cut_unique_source_faces: [usize; 2],
    pub paired_coplanar_candidate_replacement_cut_duplicate_source_records: [usize; 2],
    pub paired_coplanar_candidate_replacement_cut_fill_plans: [usize; 2],
    pub paired_coplanar_candidate_replacement_cut_added_faces: [usize; 2],
    pub paired_coplanar_candidate_shadow_repaired_replacement_cut_faces: [usize; 2],
    pub paired_coplanar_candidate_shadow_repaired_replacement_cut_source_records: [usize; 2],
    pub paired_coplanar_candidate_shadow_repaired_replacement_cut_unique_source_faces: [usize; 2],
    pub paired_coplanar_candidate_shadow_repaired_replacement_cut_duplicate_source_records: [usize; 2],
    pub paired_coplanar_candidate_shadow_repaired_replacement_cut_fill_plans: [usize; 2],
    pub paired_coplanar_candidate_shadow_repaired_replacement_cut_added_faces: [usize; 2],
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_faces: [usize; 2],
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_source_records: [usize; 2],
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_unique_source_faces: [usize; 2],
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_duplicate_source_records: [usize; 2],
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_fill_plans: [usize; 2],
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_cut_added_faces: [usize; 2],
    pub paired_coplanar_candidate_first_shadow_repair_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_second_shadow_repair_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_first_shadow_repair_path_edges: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_shadow_repair_path_edges: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_shadow_repair_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_shadow_repair_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_synthetic_contact_edges: [usize; 2],
    pub paired_coplanar_candidate_replacement_barriered_first_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_replacement_barriered_second_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_replacement_barriered_prepare_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_barriered_prepare_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_barriered_first_cut_path_overlap_components: usize,
    pub paired_coplanar_candidate_replacement_barriered_second_cut_path_overlap_components: usize,
    pub paired_coplanar_candidate_replacement_barriered_first_cut_path_overlap_component_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_barriered_second_cut_path_overlap_component_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_barriered_first_cut_path_overlap_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_barriered_second_cut_path_overlap_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_replacement_fixed_barriered_first_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_replacement_fixed_barriered_second_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_replacement_fixed_barriered_prepare_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_fixed_barriered_prepare_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_replacement_fixed_barriered_first_cut_path_overlap_components: usize,
    pub paired_coplanar_candidate_replacement_fixed_barriered_second_cut_path_overlap_components: usize,
    pub paired_coplanar_candidate_first_replacement_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_second_replacement_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_first_replacement_closed_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_second_replacement_closed_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_first_replacement_closed_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_replacement_closed_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_replacement_closed_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_replacement_closed_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_replacement_closed_cut_path_edge_adjacent_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_second_replacement_closed_cut_path_edge_adjacent_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_first_replacement_closed_cut_path_edge_left_primary_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_replacement_closed_cut_path_edge_left_primary_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_replacement_closed_cut_path_edge_right_primary_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_replacement_closed_cut_path_edge_right_primary_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_replacement_closed_cut_path_edge_left_primary_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_replacement_closed_cut_path_edge_left_primary_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_replacement_closed_cut_path_edge_right_primary_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_replacement_closed_cut_path_edge_right_primary_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_replacement_meshlib_removed_face_owner_candidates: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_replacement_meshlib_removed_face_owner_candidates: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_replacement_meshlib_removed_face_owner_candidate_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_replacement_meshlib_removed_face_owner_candidate_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_unique_source_faces: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_duplicate_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_split_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_cut_event_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_split_event_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_prefill_repair_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_open_edge_restoration_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_orphan_repair_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_fill_source_records: [usize; 2],
    pub paired_coplanar_candidate_first_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_second_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_first_closed_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_second_closed_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_first_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_closed_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_closed_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_closed_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_closed_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_cut_path_edge_adjacent_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_second_cut_path_edge_adjacent_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_first_closed_cut_path_edge_adjacent_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_second_closed_cut_path_edge_adjacent_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_first_cut_path_edge_left_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_second_cut_path_edge_left_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_first_cut_path_edge_right_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_second_cut_path_edge_right_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_first_closed_cut_path_edge_left_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_second_closed_cut_path_edge_left_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_first_closed_cut_path_edge_right_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_second_closed_cut_path_edge_right_source_faces: Vec<Vec<Vec<usize>>>,
    pub paired_coplanar_candidate_first_closed_cut_path_edge_left_primary_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_closed_cut_path_edge_left_primary_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_closed_cut_path_edge_right_primary_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_closed_cut_path_edge_right_primary_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_closed_cut_path_edge_left_primary_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_closed_cut_path_edge_left_primary_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_closed_cut_path_edge_right_primary_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_closed_cut_path_edge_right_primary_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_stitch_result_cut_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_stitch_result_cut_edge_grouped_path_lengths: Vec<usize>,
    pub paired_coplanar_candidate_stitch_result_cut_edge_grouped_closed_paths: usize,
    pub paired_coplanar_candidate_first_stitch_result_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_stitch_result_cut_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_stitch_result_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_stitch_result_cut_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_candidates: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_candidates: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_candidate_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_candidate_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_path_source_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_path_source_face_runs: Vec<Vec<[usize; 2]>>,
    pub paired_coplanar_candidate_first_stitch_result_cut_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_stitch_result_cut_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_stitch_result_cut_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_stitch_result_cut_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_stitch_result_cut_missing_source_records: [usize; 2],
    pub paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_stitch_result_cut_meshlib_removed_face_owner_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_stitch_result_cut_meshlib_removed_face_owner_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_stitch_result_cut_meshlib_removed_face_owner_missing_records: [usize; 2],
    pub paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_stitch_result_cut_edge_grouped_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_stitch_result_cut_edge_grouped_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_stitch_result_cut_edge_grouped_missing_source_records: [usize; 2],
    pub paired_coplanar_candidate_first_cut_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_cut_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_replacement_cut_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_replacement_cut_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_shadow_repaired_replacement_cut_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_shadow_repaired_replacement_cut_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_cut_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_cut_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_replacement_fill_plan_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_replacement_fill_plan_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_replacement_fill_plan_added_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_replacement_fill_plan_added_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_shadow_repaired_replacement_fill_plan_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_shadow_repaired_replacement_fill_plan_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_fill_plan_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_fill_plan_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_shadow_repaired_replacement_fill_plan_added_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_shadow_repaired_replacement_fill_plan_added_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_fill_plan_added_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_fill_plan_added_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_appended_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_appended_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_appended_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_appended_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_prefill_repair_record_details: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_prefill_repair_record_details: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_open_edge_restoration_record_details: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_open_edge_restoration_record_details: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_orphan_repair_record_details: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_orphan_repair_record_details: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_split_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_split_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_cut_event_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_cut_event_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_split_event_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_split_event_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_prefill_repair_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_prefill_repair_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_open_edge_restoration_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_open_edge_restoration_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_orphan_repair_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_orphan_repair_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_fill_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_fill_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_ready: [bool; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_matching_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_mismatched_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_missing_materialized_source_records: [usize; 2],
    pub paired_coplanar_candidate_meshlib_cut2origin_shadow_owner_remap_extra_materialized_source_records: [usize; 2],
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_appended_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_appended_source_faces: Vec<usize>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_source_face_counts: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_appended_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_appended_source_face_runs: Vec<[usize; 2]>,
    pub paired_coplanar_candidate_first_meshlib_cut2origin_shadow_owner_remap_mismatch_details: Vec<[usize; 3]>,
    pub paired_coplanar_candidate_second_meshlib_cut2origin_shadow_owner_remap_mismatch_details: Vec<[usize; 3]>,
    pub paired_coplanar_candidate_first_meshlib_valid_cut_faces: Vec<usize>,
    pub paired_coplanar_candidate_second_meshlib_valid_cut_faces: Vec<usize>,
    pub paired_coplanar_candidate_prepared_base_record_rewrite: Option<MeshlibPreparedBaseRecordRewriteDiagnostics>,
    pub paired_coplanar_candidate_replacement_prepared_base_record_rewrite: Option<MeshlibPreparedBaseRecordRewriteDiagnostics>,
    pub paired_coplanar_candidate_replacement_barriered_prepared_base_record_rewrite: Option<MeshlibPreparedBaseRecordRewriteDiagnostics>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_prepared_base_record_rewrite: Option<MeshlibPreparedBaseRecordRewriteDiagnostics>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_barriered_prepared_base_record_rewrite: Option<MeshlibPreparedBaseRecordRewriteDiagnostics>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_prepare_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_prepare_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_first_component_summaries: Vec<[usize; 4]>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_second_component_summaries: Vec<[usize; 4]>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_first_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_second_component_faces: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_fixed_barriered_first_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_fixed_barriered_second_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_fixed_barriered_selected_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_fixed_barriered_selected_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_no_contact_barrier_first_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_no_contact_barrier_second_prepare_part_dividable: bool,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_no_contact_barrier_selected_first_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_no_contact_barrier_selected_second_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_prepare_first_added_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_prepare_second_added_face_indices: Vec<usize>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_prepared_base_record_rewrite: Option<MeshlibPreparedBaseRecordRewriteDiagnostics>,
    pub paired_coplanar_candidate_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_added_fill_prepared_base_record_rewrite: Option<MeshlibPreparedBaseRecordRewriteDiagnostics>,
    pub paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_lifecycle_coverage: Vec<[usize; 9]>,
    pub paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_lifecycle_coverage: Vec<[usize; 9]>,
    pub paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_lifecycle_export_coverage: Vec<[usize; 9]>,
    pub paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_lifecycle_export_coverage: Vec<[usize; 9]>,
    pub paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_added_fill_lifecycle_export_coverage: Vec<[usize; 9]>,
    pub paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_added_fill_lifecycle_export_coverage: Vec<[usize; 9]>,
    pub paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_lifecycle_slots: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_selected_lifecycle_slots: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_lifecycle_export_slots: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_lifecycle_export_slots: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_first_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_added_fill_lifecycle_export_slots: Vec<Vec<usize>>,
    pub paired_coplanar_candidate_second_owner_remapped_shadow_repaired_replacement_slot_projected_barriered_added_fill_lifecycle_export_slots: Vec<Vec<usize>>,
    pub coplanar_cut_trial_first_skipped_faces: Vec<usize>,
    pub coplanar_cut_trial_second_skipped_faces: Vec<usize>,
    pub coplanar_cut_trial_accepted: bool,
    pub stitched_output_edges: usize,
    pub stitched_output_edges_with_two_faces: usize,
    pub stitched_output_edges_needing_splice: usize,
    pub topology_splice_ready: bool,
    pub topology_splice_missing_edges: usize,
    pub topology_splice_non_manifold_edges: usize,
    pub topology_splice_apply_ready: bool,
    pub topology_splice_verified_boundary_edges: usize,
    pub topology_splice_blocked_edges: usize,
    pub topology_splice_failed_edges: usize,
    pub topology_splice_synthetic_side_edges: usize,
    pub topology_splice_materialized_boundary_edges: usize,
    pub topology_splice_materialization_failed_edges: usize,
    pub topology_splice_exported_faces: usize,
    pub topology_splice_export_failed_faces: usize,
    pub topology_splice_edges_before_materialization: usize,
    pub topology_splice_edges_after_materialization: usize,
    pub topology_splice_deleted_synthetic_edges: usize,
    pub topology_splice_export_changed_faces: bool,
    pub topology_splice_duplicated_output_edges: usize,
    pub topology_splice_duplicate_output_face_groups: usize,
    pub topology_splice_duplicate_output_faces: usize,
    pub meshlib_topology_base_faces: usize,
    pub meshlib_topology_incoming_faces: usize,
    pub meshlib_topology_selected_first_faces: usize,
    pub meshlib_topology_selected_second_faces: usize,
    pub meshlib_topology_raw_selected_faces: [usize; 2],
    pub meshlib_topology_same_oriented_overlap_faces: [usize; 2],
    pub meshlib_topology_boundary_misses: [[usize; 2]; 2],
    pub meshlib_topology_coplanar_selection_delta_faces: [i64; 2],
    pub meshlib_topology_first_source_face_groups: usize,
    pub meshlib_topology_second_source_face_groups: usize,
    pub meshlib_topology_duplicate_first_source_faces: usize,
    pub meshlib_topology_duplicate_second_source_faces: usize,
    pub meshlib_topology_mapped_contour_edges: usize,
    pub meshlib_topology_missing_base_edges: usize,
    pub meshlib_topology_missing_incoming_edges: usize,
    pub meshlib_topology_direction_mismatches: usize,
    pub meshlib_topology_mapped_stitch_contour_edges: usize,
    pub meshlib_topology_missing_stitch_contour_edges: usize,
    pub meshlib_topology_synthetic_stitch_contour_edges: usize,
    pub meshlib_topology_stitch_direction_mismatches: usize,
    pub meshlib_topology_stitch_metadata_ready: bool,
    pub meshlib_topology_materialized_stitch_contour_edges: usize,
    pub meshlib_topology_unmaterialized_stitch_contour_edges: usize,
    pub meshlib_topology_materialized_synthetic_stitch_sides: usize,
    pub meshlib_topology_stitch_materialization_direction_mismatches: usize,
    pub meshlib_topology_stitch_materialization_ready: bool,
    pub meshlib_topology_record_rewrite_commands: usize,
    pub meshlib_topology_record_rewrite_blocked_edges: usize,
    pub meshlib_topology_record_rewrite_synthetic_sides: usize,
    pub meshlib_topology_record_rewrite_direction_mismatches: usize,
    pub meshlib_topology_record_rewrite_ready: bool,
    pub meshlib_topology_copied_edge_prepared_faces: usize,
    pub meshlib_topology_copied_edge_prepared_vertices: usize,
    pub meshlib_topology_virtual_copied_vertices: usize,
    pub meshlib_topology_copied_edge_prepared_edges: usize,
    pub meshlib_topology_copied_edge_mapped_edges: usize,
    pub meshlib_topology_copied_edges: usize,
    pub meshlib_topology_copied_edges_mapped_to_existing_output: usize,
    pub meshlib_topology_copied_edges_mapped_to_output: usize,
    pub meshlib_topology_copied_edges_missing_output_vertices: usize,
    pub meshlib_topology_copied_edge_translation_ready: bool,
    pub meshlib_topology_open_stitch_paths: usize,
    pub meshlib_topology_open_stitch_near_edge_updates: usize,
    pub meshlib_topology_open_stitch_near_edge_blocked_updates: usize,
    pub meshlib_topology_open_stitch_near_edge_ready: bool,
    pub meshlib_topology_near_stitch_update_commands: usize,
    pub meshlib_topology_near_stitch_updates_applied: usize,
    pub meshlib_topology_near_stitch_updates_failed: usize,
    pub meshlib_topology_near_stitch_updates_failed_start: usize,
    pub meshlib_topology_near_stitch_updates_failed_end: usize,
    pub meshlib_topology_near_stitch_updates_missing_previous_edges: usize,
    pub meshlib_topology_near_stitch_updates_missing_next_edges: usize,
    pub meshlib_topology_near_stitch_updates_origin_mismatches: usize,
    pub meshlib_topology_near_stitch_updates_previous_left_faces: usize,
    pub meshlib_topology_near_stitch_updates_next_right_faces: usize,
    pub meshlib_topology_near_stitch_updates_failed_other: usize,
    pub meshlib_topology_near_stitch_failed_details: Vec<MeshlibNearStitchFailureDiagnostic>,
    pub meshlib_topology_record_rewrite_applied_commands: usize,
    pub meshlib_topology_record_rewrite_failed_commands: usize,
    pub meshlib_topology_record_rewrite_failed_missing_targets: usize,
    pub meshlib_topology_record_rewrite_failed_closed_targets: usize,
    pub meshlib_topology_record_rewrite_failed_missing_sources: usize,
    pub meshlib_topology_record_rewrite_failed_other_commands: usize,
    pub meshlib_topology_record_rewrite_prepared_synthetic_targets: usize,
    pub meshlib_topology_record_rewrite_translated_face_records: usize,
    pub meshlib_topology_record_rewrite_apply_synthetic_sides: usize,
    pub meshlib_topology_record_rewrite_exported_faces: usize,
    pub meshlib_topology_record_rewrite_export_failed_faces: usize,
    pub meshlib_topology_record_rewrite_export_non_triangular_faces: usize,
    pub meshlib_topology_record_rewrite_export_left_ring_not_closed_faces: usize,
    pub meshlib_topology_record_rewrite_export_missing_origin_faces: usize,
    pub meshlib_topology_record_rewrite_export_other_failed_faces: usize,
    pub meshlib_topology_record_rewrite_export_changed_faces: bool,
    pub meshlib_topology_record_rewrite_apply_ready: bool,
    pub meshlib_topology_record_rewrite_exported_mesh_stats: Option<MeshStats>,
    pub meshlib_topology_record_rewrite_exported_mesh_health: Option<MeshHealth>,
    pub meshlib_topology_record_rewrite_packed_mesh_stats: Option<MeshStats>,
    pub meshlib_topology_record_rewrite_packed_mesh_health: Option<MeshHealth>,
    pub meshlib_topology_prepared_base_record_rewrite: MeshlibPreparedBaseRecordRewriteDiagnostics,
    pub meshlib_topology_rewrite_ready: bool,
    pub output_mesh_stats: MeshStats,
    pub output_mesh_health: MeshHealth,
    pub output_mesh_source: ExactBooleanOutputMeshSource,
    pub topology_splice_exported_mesh_stats: Option<MeshStats>,
    pub topology_splice_exported_mesh_health: Option<MeshHealth>,
    pub output_faces: usize,
    pub result_cut_paths: usize,
    pub result_cut_path_edges: usize,
    pub result_cut_closed_paths: usize,
    pub result_cut_mapped_paths: usize,
    pub result_cut_mapped_path_edges: usize,
    pub result_cut_mapped_closed_paths: usize,
    pub result_cut_paths_complete: bool,
    pub parity_ready: bool,
}
