use pyo3::prelude::*;
use pyo3::types::PyDict;

pub(super) fn set_paired_coplanar_candidate_diagnostics(
    output: &Bound<'_, PyDict>,
    diagnostics: &zennah_geometry_core::ExactBooleanPipelineDiagnostics,
) -> PyResult<()> {
    output.set_item(
        "paired_coplanar_candidate_stitch_compatible",
        diagnostics.paired_coplanar_candidate_stitch_compatible,
    )?;
    output.set_item(
        "paired_coplanar_candidate_first_prepare_part_dividable",
        diagnostics.paired_coplanar_candidate_first_prepare_part_dividable,
    )?;
    output.set_item(
        "paired_coplanar_candidate_second_prepare_part_dividable",
        diagnostics.paired_coplanar_candidate_second_prepare_part_dividable,
    )?;
    output.set_item(
        "paired_coplanar_candidate_first_cut_path_side_components",
        diagnostics.paired_coplanar_candidate_first_cut_path_side_components,
    )?;
    output.set_item(
        "paired_coplanar_candidate_second_cut_path_side_components",
        diagnostics.paired_coplanar_candidate_second_cut_path_side_components,
    )?;
    output.set_item(
        "paired_coplanar_candidate_first_cut_path_overlap_components",
        diagnostics.paired_coplanar_candidate_first_cut_path_overlap_components,
    )?;
    output.set_item(
        "paired_coplanar_candidate_second_cut_path_overlap_components",
        diagnostics.paired_coplanar_candidate_second_cut_path_overlap_components,
    )?;
    output.set_item(
        "paired_coplanar_candidate_result_cut_paths_complete",
        diagnostics.paired_coplanar_candidate_result_cut_paths_complete,
    )?;
    output.set_item(
        "paired_coplanar_candidate_output_faces",
        diagnostics.paired_coplanar_candidate_output_faces,
    )?;
    output.set_item(
        "paired_coplanar_candidate_output_area",
        diagnostics.paired_coplanar_candidate_output_area,
    )?;
    output.set_item(
        "paired_coplanar_candidate_output_volume",
        diagnostics.paired_coplanar_candidate_output_volume,
    )?;
    output.set_item(
        "paired_coplanar_candidate_self_intersections",
        diagnostics.paired_coplanar_candidate_self_intersections,
    )?;
    output.set_item(
        "paired_coplanar_candidate_self_intersections_available",
        diagnostics.paired_coplanar_candidate_self_intersections_available,
    )?;
    output.set_item(
        "paired_coplanar_candidate_active_volume_delta",
        diagnostics.paired_coplanar_candidate_active_volume_delta,
    )?;
    output.set_item(
        "paired_coplanar_candidate_preserves_active_volume",
        diagnostics.paired_coplanar_candidate_preserves_active_volume,
    )?;
    output.set_item(
        "paired_coplanar_candidate_boundary_edges",
        diagnostics.paired_coplanar_candidate_boundary_edges,
    )?;
    output.set_item(
        "paired_coplanar_candidate_nonmanifold_edges",
        diagnostics.paired_coplanar_candidate_nonmanifold_edges,
    )?;
    output.set_item(
        "paired_coplanar_candidate_duplicate_output_faces",
        diagnostics.paired_coplanar_candidate_duplicate_output_faces,
    )?;
    Ok(())
}
